// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/8/2026, 10:29:42 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/work-local/kystopia/easyalgos-web3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/work-local/kystopia/easyalgos-web3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/work-local/kystopia/easyalgos-web3/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/work-local/kystopia/easyalgos-web3/plugins/**/*.{js,ts,mjs}","D:/work-local/kystopia/easyalgos-web3/composables/**/*.{js,ts,mjs}","D:/work-local/kystopia/easyalgos-web3/utils/**/*.{js,ts,mjs}","D:/work-local/kystopia/easyalgos-web3/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/work-local/kystopia/easyalgos-web3/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/work-local/kystopia/easyalgos-web3/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/work-local/kystopia/easyalgos-web3/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;