<script setup lang="ts">
// The dot globe on the left of "module - The Solution" — Figma "Animation"
// (3199:8782), holding "The_Solution" (3201:7987).
//
// Figma draws the graphic as 3,447 individual vector dots: one per land cell of a
// perspective-projected globe, each a 2–3px ellipse, each foreshortened by where
// it sits on the sphere. Shipped as drawn that is 810 KB of SVG and 3,447 DOM
// nodes — the wrong shape twice over, because the brief for this graphic is that
// it ANIMATES, per dot, while the reader scrolls three phrases past it.
//
// So the geometry is extracted to numbers ahead of time (data/solutionGlobe.ts,
// generated by scripts/extract-globe-dots.py) and drawn to a canvas. That is the
// whole reason for the canvas: with the field as three typed arrays, any dot can
// be moved, scaled, lit or dimmed for the cost of arithmetic, and the entire field
// is a handful of fill calls per frame. 27 KB of data, one element, no DOM writes
// while the reader scrolls.
//
// It is the same division of labour as the home page's particle cluster: geometry
// is pure data, the component owns only the CLOCK-to-pixels step, and the thing
// driving it is a single number the section passes in. `t` here is the section's
// held-stretch progress, exactly as `StarMap`'s `t` is a position on a Figma
// timeline — the graphic cannot tell what moved it.
//
// ---------------------------------------------------------------------------
// PLACEHOLDER MOTION. Everything under "the wake" below is a stand-in, waiting on
// the real choreography. It was written to be replaced: `dotState` is the only
// place the per-dot animation lives, it is handed the dot's index, its place in
// the field and the two clocks, and it returns the four things the renderer knows
// how to draw (offset, scale, alpha). Drop a new body in there — or new keyframe
// tables above it, in the shape utils/keyframes.ts consumes, the way StarMap
// transcribes its Figma timeline — and nothing else in this file changes.
// ---------------------------------------------------------------------------
import { decodeGlobeField, GLOBE_FIELD, GLOBE_INK } from '~/data/solutionGlobe'

interface Props {
    /** 0..1 through the section's held stretch. Drives the whole piece. */
    t?: number
    /** Holds the ambient motion where it is. The scrubbed part of the piece keeps
     *  answering `t`, because that is the reader's own scrolling and pausing it
     *  would just look broken. */
    paused?: boolean
}
const props = withDefaults(defineProps<Props>(), { t: 0, paused: false })

/** The drawn animation frame — Figma 3199:8782, a 760 square around a field only
 *  260 tall. The air is not slack: it is the headroom the motion is authored
 *  into, so it is kept rather than cropped to the field. The section may give the
 *  box a shorter aspect where a 760 square would not fit (see `--globe-frame`);
 *  the field then centres in whatever height it gets. */
const BOX = 760
/** Where the field's own box sits inside that frame, drawn. The horizontal offset
 *  is kept verbatim from Figma (the field is not quite centred — 375.2 against
 *  the box's 380); the vertical is expressed as the 5px bias off centre that it
 *  is, so it survives the box changing shape. */
const FIELD_X = 47.883
const FIELD_BIAS_Y = 5.04

const root = ref<HTMLElement | null>(null)
const canvasRef = ref<HTMLCanvasElement | null>(null)

const field = decodeGlobeField()

// ------------------------------------------------------------------ the wake --
// Placeholder, per the note above: land coming online. A soft front crosses the
// globe as the reader scrolls, dots rising and brightening into it, the field
// breathing once it is lit. It says what the copy beside it says — thousands of
// traders, everywhere, arriving — and it gives all three phrase groups something
// moving to sit against, which a static map would not.

/** Fraction of `t` the front takes to cross. It finishes before the stage
 *  releases, so the last thing the reader sees is the whole globe lit rather than
 *  a front still halfway over it. */
const WAKE_RUN = 0.88
/** Softness of the front, as a fraction of the crossing. Wide: a hard edge reads
 *  as a wipe over a picture, a soft one as the picture filling in. */
const WAKE_EDGE = 0.16
/** Dormant and lit alpha for a cell, against GLOBE_INK.
 *
 *  The floor is higher than it looks like it should be, and the reason is the
 *  shrink below: the two multiply, so a cell at 0.3 alpha and 55% of its area
 *  carries about a tenth of the ink of a lit one, and the map reads as absent
 *  rather than as waiting. The first phrase group owns the first third of the
 *  hold and would spend it beside an empty box. At 0.42 the whole map is legibly
 *  THERE from the start and the wake brightens it, which is the reading the copy
 *  wants — the world is already full of traders. */
const DORMANT = 0.42
const LIT = 0.92
/** Extra brightness right at the front, peaking where a cell is half-woken —
 *  this is what makes the front legible as a moving thing rather than a boundary
 *  between two shades. */
const CREST = 0.5
/** How far below its place a dormant cell sits, in drawn px, and how small. The
 *  shrink is modest for the reason given on DORMANT — it compounds with the
 *  alpha, so it buys presence cheaply and costs it dearly. */
const RISE = 7
const SHRINK = 0.28
/** Ambient breathing once lit: amplitude, and the slowest/fastest period in ms. */
const BREATH = 0.16
const BREATH_MS = [2600, 5200]

/** And where the field LEAVES, on `t`.
 *
 *  Not decoration, and not optional. The page tint starts washing back to white
 *  roughly a viewport before the section's trailing edge (see usePageTint —
 *  generous on purpose, because on the home page a white line runs through that
 *  wash and wants the overlap). A field of #51567A dots is the opposite case: it
 *  is built to sit on the dark, and left up it spends the end of the module
 *  stranded on a mid-grey page, which is exactly as bad as it sounds.
 *
 *  So the field's last act is to go, on the same beat the last phrase group
 *  clears. The stage then releases empty, and the wash plays out over flat dark
 *  with nothing on it to spoil. `RESOLVED_T` in ForDevSolutionSection is the
 *  other side of this number — the frame the stacked layout rests on, which has
 *  to be before the field starts leaving. */
const EXIT_FROM = 0.94
const EXIT_TO = 1

/** Per-dot constants, derived once: where the cell falls in the wake order, and
 *  its own breathing phase and rate. Kept as arrays beside the geometry so the
 *  frame loop reads flat memory and allocates nothing. */
const wakeAt = new Float32Array(field.count)
const breathPhase = new Float32Array(field.count)
const breathRate = new Float32Array(field.count)

{
    // A cheap deterministic hash per index — same field on every load, and no
    // 3,447-entry random table to ship.
    const hash = (i: number, salt: number) => {
        const v = Math.sin((i + 1) * salt) * 43758.5453
        return v - Math.floor(v)
    }
    for (let i = 0; i < field.count; i++) {
        // West to east, with a southward lean and a per-cell scatter: the front
        // arrives as a ragged diagonal, like a terminator line, rather than as a
        // vertical bar. The scatter is what dissolves it at the edges.
        const west = field.x[i] / GLOBE_FIELD.width
        const south = field.y[i] / GLOBE_FIELD.height
        wakeAt[i] = west * 0.82 + south * 0.1 + hash(i, 12.9898) * 0.08
        breathPhase[i] = hash(i, 78.233) * Math.PI * 2
        breathRate[i] = BREATH_MS[0] + hash(i, 45.164) * (BREATH_MS[1] - BREATH_MS[0])
    }
}

function smoothstep(edge0: number, edge1: number, x: number) {
    const u = Math.min(1, Math.max(0, (x - edge0) / (edge1 - edge0)))
    return u * u * (3 - 2 * u)
}

/** The per-dot animation, and the ONLY place it lives.
 *
 *  @param i       the cell's index into the field
 *  @param t       0..1 through the section's held stretch
 *  @param clockMs ambient wall time, ms — stopped when the piece is off screen or
 *                 paused, so it is motion time rather than elapsed time
 *  @returns       drawn-pixel offset, a scale on the cell's own radii, and alpha.
 *                 Alpha <= 0 means "skip", which is how a real choreography would
 *                 clear the field.
 */
function dotState(i: number, t: number, clockMs: number) {
    const front = (t / WAKE_RUN) * (1 + WAKE_EDGE * 2) - WAKE_EDGE
    const woken = smoothstep(wakeAt[i] - WAKE_EDGE, wakeAt[i] + WAKE_EDGE, front)

    // Peaks at half-woken, zero at both ends.
    const crest = woken * (1 - woken) * 4
    const breath = 1 + BREATH * woken * Math.sin((clockMs / breathRate[i]) * Math.PI * 2 + breathPhase[i])
    const leaving = 1 - smoothstep(EXIT_FROM, EXIT_TO, t)

    return {
        dy: -RISE * (1 - woken),
        scale: (1 - SHRINK * (1 - woken)) * (1 + crest * 0.18),
        alpha: (DORMANT + (LIT - DORMANT) * woken + CREST * crest) * breath * leaving
    }
}

// ------------------------------------------------------------------ renderer --
// Cells are batched by quantised alpha: one Path2D per bucket, one fill per
// bucket. The alternative — set a fill style and fill per cell — is 3,447 state
// changes a frame. Buckets of 1/16 are invisible on a 2px dot and turn the whole
// field into at most sixteen fills.
//
// Measured, on the full 760 box with every cell inked (the most expensive frame
// the piece has): 2.0ms median, 2.8ms worst of a 16.7ms budget. Worth knowing
// before adding per-cell work in `dotState` — there is room, but not a lot of it,
// and the honest ceiling is the arithmetic rather than the fills.
const BUCKETS = 16
const INK = (() => {
    const hex = GLOBE_INK.replace('#', '')
    return [0, 2, 4].map((at) => parseInt(hex.slice(at, at + 2), 16))
})()

let ctx: CanvasRenderingContext2D | null = null
let cssWidth = 0
let cssHeight = 0
let scale = 1
let rafId = 0
let lastFrame = 0
/** Ambient time, accumulated only while the piece is on screen and running — so
 *  scrolling away and back resumes the breathing instead of snapping it to a new
 *  phase. Same reasoning as the particle cluster's `motionMs`. */
let clockMs = 0
let onScreen = false
let reduced = false
let io: IntersectionObserver | null = null
let ro: ResizeObserver | null = null

function draw() {
    if (!ctx || cssWidth <= 0) return

    ctx.clearRect(0, 0, cssWidth, cssHeight)

    // The field is scaled by WIDTH against the drawn 760 frame, then centred in
    // whatever height the box has. At the drawn square this is pixel-exact to
    // Figma; at a shorter box it keeps the field's size and loses only air.
    const k = cssWidth / BOX
    const originX = FIELD_X * k
    const originY = (cssHeight - GLOBE_FIELD.height * k) / 2 + FIELD_BIAS_Y * k

    const paths: (Path2D | null)[] = new Array(BUCKETS).fill(null)
    const t = Math.min(1, Math.max(0, props.t))

    for (let i = 0; i < field.count; i++) {
        const state = dotState(i, t, clockMs)
        if (state.alpha <= 0.01) continue

        const bucket = Math.min(BUCKETS - 1, Math.round(state.alpha * (BUCKETS - 1)))
        const path = paths[bucket] || (paths[bucket] = new Path2D())
        const cx = originX + field.x[i] * k
        const cy = originY + (field.y[i] + state.dy) * k
        const rx = Math.max(0.35, field.rx[i] * state.scale * k)
        const ry = Math.max(0.35, field.ry[i] * state.scale * k)
        // The moveTo is not optional. `ellipse` on a path that already has a
        // subpath joins the two with a straight line, so a bucket of 200 cells
        // without it draws 199 hairlines across the map — which looks exactly like
        // a smear. Landing the pen on the arc's own start point (angle 0, i.e.
        // cx + rx) makes that joining line zero-length.
        path.moveTo(cx + rx, cy)
        path.ellipse(cx, cy, rx, ry, 0, 0, Math.PI * 2)
    }

    for (let b = 0; b < BUCKETS; b++) {
        const path = paths[b]
        if (!path) continue
        ctx.fillStyle = `rgba(${INK[0]}, ${INK[1]}, ${INK[2]}, ${(b / (BUCKETS - 1)).toFixed(3)})`
        ctx.fill(path)
    }
}

function frame(now: number) {
    // Clamp the delta: a backgrounded tab hands back a multi-second gap on
    // return, which would jump the breathing rather than continue it.
    clockMs += lastFrame ? Math.min(now - lastFrame, 64) : 0
    lastFrame = now
    draw()
    rafId = requestAnimationFrame(frame)
}

function stop() {
    if (rafId) cancelAnimationFrame(rafId)
    rafId = 0
    lastFrame = 0
}

/** Run the ambient loop only when it can be seen and has not been paused.
 *  Everything else redraws on demand — see the `t` watcher. */
function sync() {
    if (onScreen && !props.paused && !reduced) {
        if (!rafId) rafId = requestAnimationFrame(frame)
    } else {
        stop()
    }
}

function resize() {
    const el = canvasRef.value
    const box = root.value
    if (!el || !box) return
    const rect = box.getBoundingClientRect()
    if (rect.width <= 0) return
    // Capped at 2: past that the extra pixels are invisible on a 2px dot and the
    // fill cost is real.
    const dpr = Math.min(2, window.devicePixelRatio || 1)
    cssWidth = rect.width
    cssHeight = rect.height
    scale = dpr
    el.width = Math.round(cssWidth * dpr)
    el.height = Math.round(cssHeight * dpr)
    el.style.width = `${cssWidth}px`
    el.style.height = `${cssHeight}px`
    ctx = el.getContext('2d')
    // One transform, so everything downstream works in CSS pixels.
    ctx?.setTransform(scale, 0, 0, scale, 0, 0)
    draw()
}

// Scroll moves `t`; when the ambient loop is stopped (off screen, paused, or
// reduced motion) nothing else would repaint, so the scrubbed part needs its own
// redraw. While the loop IS running this is a no-op the next frame absorbs.
watch(
    () => props.t,
    () => {
        if (!rafId) draw()
    }
)
watch(() => props.paused, sync)

onMounted(() => {
    reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches
    resize()

    ro = new ResizeObserver(resize)
    if (root.value) ro.observe(root.value)

    if (reduced) {
        // Resolved, once: the field lit and still. `t` is pinned at 1 by
        // `usePinnedPhases` in this mode, so this draw is the end state.
        draw()
        return
    }

    io = new IntersectionObserver(
        (entries) => {
            for (const entry of entries) onScreen = entry.isIntersecting
            sync()
        },
        { rootMargin: '200px 0px' }
    )
    io.observe(root.value!)
})

onBeforeUnmount(() => {
    stop()
    io?.disconnect()
    ro?.disconnect()
    io = null
    ro = null
})
</script>

<template>
    <!-- Decoration over real copy: hidden from assistive tech outright. The
         argument it makes is made in words by the phrases beside it.
         `--globe-frame` is the box's aspect ratio, set by the section — the drawn
         760 square where there is room for it, shorter where there is not. -->
    <div
        ref="root"
        class="pointer-events-none relative w-full"
        style="aspect-ratio: var(--globe-frame, 1)"
        aria-hidden="true"
    >
        <canvas ref="canvasRef" class="absolute inset-0 block h-full w-full" />
    </div>
</template>
