<script setup lang="ts">
// The dot globe on the left of "module - The Solution" — Figma "Animation"
// (3199:8782), holding "The_Solution" (3201:7987). Both states of it are drawn
// side by side in 3237:8038.
//
// Figma draws the graphic as 3,447 individual vector dots: one per land cell of a
// perspective-projected globe, each a 2–3px ellipse, each foreshortened by where
// it sits on the sphere. Shipped as drawn that is 810 KB of SVG and 3,447 DOM
// nodes — the wrong shape twice over, because the brief for this graphic is that
// it ANIMATES, per dot, while the reader scrolls a run of phrases past it.
//
// So the geometry is extracted to numbers ahead of time (data/solutionGlobe.ts,
// generated by scripts/extract-globe-dots.py) and drawn to a canvas. That is the
// whole reason for the canvas: with the field as three typed arrays, any dot can
// be moved, scaled, lit or dimmed for the cost of arithmetic, and the entire field
// is a handful of fill calls per frame. 27 KB of data, one element, no DOM writes
// while the reader scrolls.
//
// It is the same division of labour as the home page's particle cluster: geometry
// is pure data, the component owns only the CLOCK-to-pixels step, and the things
// driving it are numbers the section passes in.
//
// TWO numbers and a switch, and the split between them is the point of this piece
// rather than an implementation detail — three kinds of time, named:
//
//   wake     the wave. TRIGGERED, not scrubbed — it runs on a clock the section
//            starts the moment the pinned stage comes to rest, and plays out at
//            its own pace whatever the reader does next. A wave read off scroll
//            position is not a wave: it stops when the reader stops, runs
//            backwards when they scroll back, and the faster they read the faster
//            it breaks. This one is an event with a beginning and an end.
//   t        the scroll through the held stretch, and the departure is ALL it is
//            used for. See EXIT_FROM — leaving is a fact about where the page has
//            got to, not about the wave, so it stays on the scroll.
//   beacons  the lights that climb off the field, and the only thing here that
//            LOOPS. Not an event and not a scrub: a state a phrase group is in,
//            which the section turns on when that group takes the stage and off
//            when it leaves. See BEACON_ROOF and `stepBeacons`.
//   cards     the same loop with the trade card in it, which is the third group's
//            state of the graphic rather than the second's. It is a second switch
//            rather than a mode number because that is what it is: the light and
//            the card are the same event, and the card is a stretch inserted into
//            the middle of it. See CARD_SHOW_MS.
import { decodeGlobeField, GLOBE_FIELD, GLOBE_INK } from '~/data/solutionGlobe'
import { columnParity } from '~/utils/globeColumns'

interface Props {
    /** 0..1 through the wave's own run. Clock-driven by the section. */
    wake?: number
    /** 0..1 through the section's held stretch. Drives the departure and nothing
     *  else, so anything below EXIT_FROM means "staying" — the layouts with no
     *  held stretch to report pass 0. */
    t?: number
    /** How much of the loop runs, which is the same question as which phrase
     *  group is on stage — Figma draws the graphic once per group and each one
     *  ADDS to the last, so this is a ladder rather than a set of switches:
     *
     *    off       the field alone. The heading's state, and the last group's.
     *    lights    lights climb off the map and stop.      (3237:11532)
     *    trades    each light arrives at a trade card.     (3240:18444)
     *    payouts   each card then sends its profit home.   (3240:21900)
     *
     *  One prop rather than three booleans because there is no such thing as
     *  cards without lights, or routes without cards — as flags, five of the eight
     *  combinations would be states nobody drew. Turning it down lets whatever is
     *  in flight finish rather than cutting it. */
    loop?: 'off' | 'lights' | 'trades' | 'payouts'
    /** Holds the ambient breathing where it is. */
    paused?: boolean
}
const props = withDefaults(defineProps<Props>(), {
    wake: 0,
    t: 0,
    loop: 'off',
    paused: false
})

/** The rungs, read as questions rather than as string comparisons scattered
 *  through the frame loop. */
const looping = () => props.loop !== 'off'
const loopingCards = () => props.loop === 'trades' || props.loop === 'payouts'
const loopingRoutes = () => props.loop === 'payouts'

/** The drawn animation frame — Figma 3199:8782, a 760 square around a field only
 *  260 tall. The air is not slack: it is the headroom the motion is authored
 *  into, so it is kept rather than cropped to the field. The section may give the
 *  box a shorter aspect where a 760 square would not fit (see `--globe-frame`);
 *  the field then centres in whatever height it gets. */
const BOX = 760
/** Where the field's own box sits inside that frame, drawn. The horizontal offset
 *  is kept verbatim from Figma (the field is not quite centred — 375.2 against
 *  the box's 380); the vertical is expressed as the 5px bias off centre that it
 *  is, so it survives the box changing shape. */
const FIELD_X = 47.883
const FIELD_BIAS_Y = 5.04

const root = ref<HTMLElement | null>(null)
const canvasRef = ref<HTMLCanvasElement | null>(null)

const field = decodeGlobeField()

// ------------------------------------------------------------------ the wave --
// Land coming online. A front crosses the globe once, west to east; every cell it
// passes over is a lighter colour on the far side than it was on the near one, and
// every other cell down each column is thrown up and dropped back as it goes,
// dragging a short fading trail of itself behind it. It says what the copy beside
// it says — thousands of traders, everywhere, arriving — and it leaves the field
// lit for the phrase groups that follow.
//
// Light and throw are deliberately not the same set of cells: see `moves`.
//
// The whole animation lives in `dotState`: it is handed the cell's index, the
// wave's progress and the ambient clock, and returns the three things the
// renderer knows how to draw (offset, scale, and a position on the ink ramp).

/** The ink ramp, and the one place the field's colour lives.
 *
 *  Figma draws the two states as two flat colours on identical geometry — nothing
 *  moves between them and nothing fades, the dots are simply Tinted/900 before and
 *  Tinted/700 after (3237:8042 and 3237:11534). So the resting field is a solid
 *  colour rather than the lit colour held at low alpha: those are not the same
 *  thing on a dark ground, and the drawn one is the more violet of the two.
 *
 *  CREST is the overshoot at the front itself, a step brighter than lit
 *  (Tinted/500). It is what makes the wave legible as a moving thing rather than
 *  as a boundary between two shades. */
const IDLE_INK = '#2F2A4A' // Tinted/900
const LIT_INK = GLOBE_INK // Tinted/700, the colour the field is exported in
const CREST_INK = '#7A7FA3' // Tinted/500

/** Softness of the front, as a fraction of the crossing, and the per-cell scatter
 *  applied to the order (below). The edge is what the wave's thickness IS: wide
 *  reads as the picture filling in, narrow as a ridge rolling across it. This is
 *  narrow, because a ridge is what the jump below needs to be attached to. The
 *  scatter then dissolves its ends so it is a swell rather than a ruler. */
const WAKE_EDGE = 0.12

/** How far a cell is thrown as the front passes, in drawn px, and how much bigger
 *  it gets at the top of the throw.
 *
 *  12 is about two and a half rows of the lattice — enough that a thrown cell is
 *  clearly out of line with the ones it was beside, and no more. It was 24, which
 *  is nearly six rows: at that height the thrown cell lands among its neighbours
 *  three rows up and the front reads as a band of map sliding rather than as dots
 *  leaving it. Note that the throw is spent entirely ON the front — a cell is at
 *  its place before the wave reaches it and back at its place after, because
 *  Figma's two states are the same geometry and the motion is what happens in
 *  between. */
const JUMP = 12
const CREST_GROW = 0.35

/** The trail behind a thrown cell: how many ghosts of its own recent past are
 *  drawn under it, how far back on the crossing each one sits, where the first
 *  one starts on the alpha ramp, and how much each one shrinks.
 *
 *  A ghost is not a blur and not a smear — it is the SAME cell, asked for an
 *  earlier front, which is why the lag is measured in the crossing's units rather
 *  than in milliseconds. It therefore lands exactly on the arc the cell has
 *  travelled: it curves over with it at the top of the throw and closes up under
 *  it as it lands, for free, with nothing kept between frames and nothing to fall
 *  out of sync. It also means the trail is a constant fraction of the MOTION — the
 *  wave's duration lives in the section, and a faster wave gets a proportionally
 *  shorter trail rather than a longer one.
 *
 *  Three at 0.018 of the crossing is about four frames of the throw — enough to
 *  read which way the cell is going, short enough that the front stays a ridge
 *  rather than becoming a band of smeared dots. And they are the only per-cell
 *  thing here drawn on alpha rather than on the ink ramp, which is the honest way
 *  round: a trail IS the cell not being there any more. */
const TRAIL_STEPS = 3
const TRAIL_LAG = 0.018
const TRAIL_ALPHA = 0.42
const TRAIL_TAPER = 0.12

/** Ambient breathing once lit: amplitude as a fraction of the idle-to-lit
 *  distance on the ramp, and the slowest/fastest period in ms. It shimmers the
 *  colour rather than the alpha, which is the same reasoning as the ramp itself. */
const BREATH = 0.18
const BREATH_MS = [2600, 5200]

/** And where the field LEAVES, on `t`.
 *
 *  Not decoration, and not optional. The page tint starts washing back to white
 *  roughly a viewport before the section's trailing edge (see usePageTint —
 *  generous on purpose, because on the home page a white line runs through that
 *  wash and wants the overlap). A field of Tinted/700 dots is the opposite case:
 *  it is built to sit on the dark, and left up it spends the end of the module
 *  stranded on a mid-grey page, which is exactly as bad as it sounds.
 *
 *  So the field's last act is to go, on the same beat the last phrase group
 *  clears. The stage then releases empty, and the wash plays out over flat dark
 *  with nothing on it to spoil. */
const EXIT_FROM = 0.94
const EXIT_TO = 1

// --------------------------------------------------------------- the beacons --
// Lights that climb off the field and stop. Figma 3237:11532 — the second phrase
// group's state of this graphic, and only that one's — draws twenty-nine of them:
// 2 wide, 42 tall, pill-capped, a gradient running from #BC78FF at the top to the
// same colour at zero alpha at the bottom, each one standing ON a dot of the field
// (checked against the export: every beam's foot is within a pixel of a dot
// centre).
//
// That drawing is one FRAME of something, and the shape of the thing it is a frame
// of is the brief: a dot changes colour, a light leaves it and climbs, dragging a
// trail that stays anchored at the dot — which is why the drawn beam is the full
// 42 with its faded end still down on the map. When the light reaches the roof it
// stops, the trail catches it up, and what is left winks out. Then that dot is
// done and another somewhere else starts.
//
// So the drawn 42 is the ROOF, not a length, and the gradient is not decoration on
// a bar: it is where the light has been. One beacon is four spans of time in a
// row, and the whole of the animation is `at` against those four numbers.

/** The light's colour, and its two ends. Flat #BC78FF at the head, the same colour
 *  at zero alpha at the tail — Figma's stops are 2.4% and 102.6%, i.e. the fade
 *  runs the entire beam and is very slightly clipped at the foot, which at this
 *  size is a rounding difference and not a thing to reproduce. */
const BEACON_INK = '#BC78FF'
const BEACON_GONE = 'rgba(188, 120, 255, 0)'

/** How far above its dot a light climbs before it stops, and how wide it is —
 *  both in drawn px, both verbatim from the drawn rectangle. 42 against a field
 *  260 tall is a sixth of it, which is why these read as leaving the map rather
 *  than as part of its texture — the wave's throw, next to them, is 12. */
const BEACON_ROOF = 42
const BEACON_WIDTH = 2

/** The four spans, in ms.
 *
 *  SPARK is the dot changing colour with nothing above it yet, which is what makes
 *  the climb read as coming OUT of the field rather than passing over it. CLIMB
 *  is the light going up, easing out, with the trail still anchored at the dot.
 *  CATCH is the light parked at the roof while the trail closes on it — and the
 *  dot letting go of its colour, because by then the light is what is lit, not the
 *  map. FADE is the last of it going out.
 *
 *  With a card on the end (see CARD_HOLD_AT_ROOF_MS) the whole of it is inserted
 *  between CLIMB and CATCH — the light holds at the roof for as long as the card
 *  is up, and the trail closes on it as the card leaves. */
const BEACON_SPARK_MS = 170
const BEACON_CLIMB_MS = 900
const BEACON_CATCH_MS = 340
const BEACON_FADE_MS = 260
/** REST is what the beacon does afterwards, and it is a MULTIPLE of its own run
 *  rather than a span in ms: the run is two and a half times longer with a card on
 *  the end of it, and a fixed rest would make the third group's map two and a half
 *  times busier than the second's for no reason anybody chose. As fractions, the
 *  field is about as busy either way — a beacon rests for between a sixth of its
 *  run and about one and a half of them. */
const BEACON_REST = [0.15, 1.4]

// ------------------------------------------------------------ the trade card --
// What a light arrives at on the THIRD phrase group — Figma 3240:18444, with the
// three states drawn out separately as 3261:22473 / 22483 / 22480.
//
// A 24-tall pill: 8 of padding, an 8px bubble, 8 of gap, the pair, 8 of padding —
// 73 wide with "BTCUSD" in it. Measured against the drawn slide, every card sits
// with its BOTTOM EDGE on the head of its beam and its centre on the beam's x, so
// the pill balances on the tip of the light rather than hanging beside it.
//
// The three drawn states are three widths as much as three appearances: state 01
// and 02 are 24 wide (the text layer is hidden, so the auto-layout hugs the
// bubble) and state 03 is 73. So the card GROWS as the pair types in, and it
// grows from the middle, because that is the only way to start centred on the
// beam and end centred on it.
//
//   1  the bubble arrives, a third of a second BEFORE the light stops climbing —
//      see CARD_LEAD_MS, which is what makes the light arrive into a card rather
//      than the card appear after a light
//   2  the container fades in around it, background and stroke together
//   3  the pair types in, a letter at a time on an ease-in-out, the pill widening
//      as it goes
//   4  it holds, then lifts and goes out — and the light's trail closes up
//      underneath it on the same beat, so the two leave as one thing.

/** The drawn box, in drawn px. Height and paddings are Figma's; the WIDTH is
 *  measured at runtime from the text, which is what makes the growth work and what
 *  keeps a pair of another length (or a fallback font) inside its pill instead of
 *  spilling out of it. */
const CARD_H = 24
const CARD_PAD = 8
const CARD_GAP = 8
const CARD_BUBBLE = 8
/** The bubble's ring is a 4px SPREAD shadow at 10%, i.e. a circle twice the
 *  bubble's size behind it. Drawn as that circle, because it is one. */
const CARD_RING = 4
const CARD_STROKE_W = 2

const CARD_FILL = 'rgba(14, 14, 16, 0.85)'
const CARD_STROKE = '#3E4153'
const CARD_BUBBLE_INK = '#C5CDD5'
const CARD_RING_INK = 'rgba(98, 103, 143, 0.1)'
const CARD_TEXT_INK = '#C9C2FF' // Violet/200
/** Roboto Medium 10 at half a pixel of tracking — the drawn type, and the one
 *  weight of Roboto this site ships besides the body 400. Both are in DRAWN px
 *  like every other number here, so the draw scales them by `k` with the rest of
 *  the graphic; a fixed 10px would grow relative to the card as the box shrinks.
 *  `onMounted` asks for the face explicitly: canvas text does not trigger a font
 *  load the way the DOM does, so without that the first cards would be drawn in
 *  the fallback and measured against it. */
const CARD_FONT_PX = 10
const CARD_FONT_FACE = '500 %px Roboto, sans-serif'
const CARD_TRACKING = 0.5

/** The four spans of the card, in ms, and how far it lifts on the way out.
 *
 *  TYPE is the whole pair rather than one letter, so the timeline does not change
 *  length with the string — "quickly, letter by letter" is about what the reader
 *  sees, and six letters in 270ms is fast enough to read as typing and short
 *  enough not to be a wait. HOLD is the two seconds asked for; EXIT is the lift
 *  and the fade, quick because the card has already said what it came to say. */
const CARD_DOT_MS = 140
const CARD_BOX_MS = 180
const CARD_TYPE_MS = 270
const CARD_HOLD_MS = 2000
const CARD_EXIT_MS = 280
const CARD_EXIT_LIFT = 10

/** How far AHEAD of the light's arrival the card starts.
 *
 *  The card is drawn at the roof from its first frame — its place is where the
 *  light is going, not where the light is — so this is purely a question of when
 *  the sequence above starts running. Begun on arrival, the bubble is a thing that
 *  happens after the light has stopped and the two read as two events. Begun
 *  early, the bubble is fading up while the head still has visible ground to
 *  cover: the light arrives INTO a card that is already forming, which is one
 *  event.
 *
 *  The size of it is set by the climb's ease-out rather than by taste. That curve
 *  spends its last third of a second on the final few per cent of the rise, so a
 *  lead of 100 or 200 would fire while the light is, to the eye, already stopped —
 *  the right timing on paper and no visible change. At 420 the head is a tenth of
 *  the rise short when the bubble starts, about 4 drawn px, which is far enough to
 *  read as still climbing. */
const CARD_LEAD_MS = 420

/** Everything before the exit. Less the lead, this is also exactly how long the
 *  light waits at the roof before its trail is allowed to catch up — the card
 *  starts early and still ends on the same beat as the light it stands on. */
const CARD_SHOW_MS = CARD_DOT_MS + CARD_BOX_MS + CARD_TYPE_MS + CARD_HOLD_MS
const CARD_HOLD_AT_ROOF_MS = CARD_SHOW_MS - CARD_LEAD_MS

/** What the cards say — Diego's list. Figma draws BTCUSD on every one of them,
 *  which is a component instance rather than a claim that the world trades one
 *  symbol: a map of twenty identical tickers reads as a repeated graphic instead
 *  of as trades arriving.
 *
 *  Every one is six characters, so every card comes out the drawn 73 wide. Adding
 *  one that is not (a metal like XAGUSD is still six; something like EURGBP.x is
 *  not) costs nothing — the pill is measured from the text, see `drawCards` — but
 *  it will be a different width from its neighbours. */
const CARD_PAIRS = [
    'ETHUSD',
    'BTCUSD',
    'EURUSD',
    'GBPUSD',
    'USDJPY',
    'USDCHF',
    'USDCAD',
    'AUDUSD',
    'NZDUSD',
    'AUDCAD',
    'XAUUSD'
]

// ------------------------------------------------------------ the profit route --
// Where the money goes — Figma 3240:21900, the LAST group's state, drawn there as
// eighteen vectors named "Profit Route": one per trade card, each a 2px gold arc
// from the card's centre-top, swinging high over the map and coming down on a
// single point. Every one of them ends at the same place, which is the argument
// the group's copy makes in words ("You get paid on every trade, for life") drawn
// as a shape: many sources, one destination.
//
// The drawn arc is a cubic with hand-dragged handles, and its gradient runs from
// the colour at ZERO alpha at the card end to full at the hub end — which is not a
// decorative fade, it is a trail. The drawn state is the moment the light arrives:
// everything behind it is the path it took, fading out the further back you look.
// So the poster is one frame of exactly the animation asked for, and the animation
// is the poster with the arrival moved.

/** The hub, in the field's own drawn coordinates — read off the convergence point
 *  of the eighteen drawn routes (481, 316.5 in the animation frame), which sits
 *  within half a pixel of a cell of the map. Kept as a POSITION rather than as a
 *  cell index so that re-exporting the field cannot silently move the destination
 *  to a different country; the nearest cell to this point is found at runtime. */
const ROUTE_HUB_AT = [435.12, 76.41]

const ROUTE_INK = '#FFE389'
const ROUTE_GONE = 'rgba(255, 227, 137, 0)'
const ROUTE_WIDTH = 2

/** How high the arc swings, as the height of its apex above the straight line
 *  between its ends.
 *
 *  Measured off two of the drawn routes — the longest and one of the shortest —
 *  which come out at 27% and 43% of their own chord. Short hops bulge relatively
 *  more, or they would read as straight lines at map scale, so this is a fraction
 *  with a floor rather than a fraction. The arc itself is a quadratic: Figma's are
 *  cubics, but with the apex in the same place and the same ends, the difference
 *  over 300px of map is not visible, and a quadratic has one handle to reason
 *  about instead of two. */
const ROUTE_LIFT_FRAC = 0.27
const ROUTE_LIFT_MIN = 45

/** The flight, and the same three-part departure the lights have: the head runs
 *  the arc, the trail stays anchored at the card behind it, then the trail is let
 *  go and the whole thing fades. Timed to finish inside the card's two seconds on
 *  screen, so nothing is still flying when the card leaves. */
const ROUTE_FLY_MS = 850
const ROUTE_CATCH_MS = 420
const ROUTE_FADE_MS = 260
/** And when it leaves: the instant the pair finishes typing, which is what "when a
 *  trade pair is shown" means — the card has said what the trade was, and the
 *  money goes. */
const ROUTE_FROM_MS = CARD_DOT_MS + CARD_BOX_MS + CARD_TYPE_MS

/** The destination's own colour change, which happens ONCE — it is not part of any
 *  beacon's loop. It comes up when the group takes the stage and goes back down
 *  when it leaves, and in between it simply stays lit: the routes need somewhere
 *  to be going before the first one gets there. */
const HUB_LIGHT_MS = 700
const HUB_RING = 4
const HUB_RING_INK = 'rgba(255, 227, 137, 0.12)'

/** The cell the routes come home to: the nearest one to the drawn convergence
 *  point. */
const hubDot = (() => {
    let best = 0
    let bestD = Infinity
    for (let i = 0; i < field.count; i++) {
        const dx = field.x[i] - ROUTE_HUB_AT[0]
        const dy = field.y[i] - ROUTE_HUB_AT[1]
        const d = dx * dx + dy * dy
        if (d < bestD) {
            bestD = d
            best = i
        }
    }
    return best
})()

/** How far through its one colour change the destination is, 0..1. Advanced by
 *  the frame loop in both directions — see `stepBeacons`. */
let hubLit = 0

/** How many are kept in the air. Figma's twenty-nine is a frame rather than a
 *  count, and a beacon spends about as long resting as running (1.7s of life
 *  against a rest averaging 1.3s), so a pool of thirty-six sits around twenty on
 *  the field at any moment and only the busiest of them reaches the drawn
 *  density. Raising this does not make the loop faster, it makes the map busier —
 *  the two are separate on purpose. */
const BEACON_COUNT = 36

/** Per-dot constants, derived once: where the cell falls in the wave's order, and
 *  its own breathing phase and rate. Kept as arrays beside the geometry so the
 *  frame loop reads flat memory and allocates nothing. */
const wakeAt = new Float32Array(field.count)
const breathPhase = new Float32Array(field.count)
const breathRate = new Float32Array(field.count)

{
    // A cheap deterministic hash per index — same field on every load, and no
    // 3,447-entry random table to ship.
    const hash = (i: number, salt: number) => {
        const v = Math.sin((i + 1) * salt) * 43758.5453
        return v - Math.floor(v)
    }
    for (let i = 0; i < field.count; i++) {
        // West to east, with a southward lean and a per-cell scatter: the front
        // arrives as a ragged diagonal, like a terminator line, rather than as a
        // vertical bar.
        //
        // The scatter is SMALL — a fiftieth of the crossing against a crest band
        // a quarter of it wide — and that ratio is the difference between a wave
        // and a mess. Neighbouring cells have to be at nearly the same point of
        // the throw or the band is a spray of dots at every height rather than
        // one ridge lifting; at 0.05 the dense parts of the map (Brazil, the
        // eastern seaboard) turned to noise the moment JUMP was worth looking at.
        const west = field.x[i] / GLOBE_FIELD.width
        const south = field.y[i] / GLOBE_FIELD.height
        wakeAt[i] = west * 0.88 + south * 0.1 + hash(i, 12.9898) * 0.02
        breathPhase[i] = hash(i, 78.233) * Math.PI * 2
        breathRate[i] = BREATH_MS[0] + hash(i, 45.164) * (BREATH_MS[1] - BREATH_MS[0])
    }
}

/** WHICH cells are thrown: every other one down each column of the lattice.
 *
 *  The light is untouched by this — the wave's colour still crosses all 3,447
 *  cells, because Figma's two states are the whole map before and the whole map
 *  after, and a field that lit in stripes would simply be wrong at the end. Only
 *  the THROW is thinned. With every cell lifted there is nothing left at rest for
 *  the displacement to be read against, and a band of map that moves together
 *  reads as the map moving; leaving every other cell where it was gives the thrown
 *  ones something to be measured by, and the throw then reads as dots jumping out
 *  of the field rather than as the field flexing.
 *
 *  Which cells those are is a fact about the drawn lattice rather than about the
 *  motion, and finding them is not free — see utils/globeColumns.ts, which is also
 *  why it is not done here. */
const moves = columnParity(field)

function smoothstep(edge0: number, edge1: number, x: number) {
    const u = Math.min(1, Math.max(0, (x - edge0) / (edge1 - edge0)))
    return u * u * (3 - 2 * u)
}

/** The front's position in the field's own units. Widened by the edge at both
 *  ends so that wake 0 leaves every cell untouched and wake 1 has the front clear
 *  of the last of them — and it is the front rather than the wake that everything
 *  below is written against, because the trail reads at fronts the wave has
 *  already been past. */
function frontAt(wake: number) {
    return wake * (1 + WAKE_EDGE * 2) - WAKE_EDGE
}

/** How far through its throw a cell is with the front here: 0 before it arrives,
 *  1 once it has gone. Broken out of `dotState` for the trail, which asks for it
 *  at moments the cell has already left. */
function wokenAt(i: number, front: number) {
    return smoothstep(wakeAt[i] - WAKE_EDGE, wakeAt[i] + WAKE_EDGE, front)
}

/** Peaks at half-woken, zero at both ends: the cell is on the front exactly once,
 *  and everything that makes the wave a wave hangs off this. */
function crestOf(woken: number) {
    return woken * (1 - woken) * 4
}

/** The per-dot animation, and the ONLY place it lives.
 *
 *  @param i       the cell's index into the field
 *  @param front   the front's position, from `frontAt`
 *  @param clockMs ambient wall time, ms — stopped when the piece is off screen or
 *                 paused, so it is motion time rather than elapsed time
 *  @returns       drawn-pixel offset, a scale on the cell's own radii, and `ink`:
 *                 a position on the ramp, 0 idle, 1 lit, 2 crest.
 */
function dotState(i: number, front: number, clockMs: number) {
    const woken = wokenAt(i, front)
    const crest = crestOf(woken)
    const breath = 1 + BREATH * woken * Math.sin((clockMs / breathRate[i]) * Math.PI * 2 + breathPhase[i])

    // The throw — and only the throw — is every other cell down the column; see
    // `moves`. The ink below is the whole field, front and all.
    const thrown = moves[i] ? crest : 0

    return {
        dy: -JUMP * thrown,
        scale: 1 + CREST_GROW * thrown,
        ink: Math.min(2, woken * breath + crest)
    }
}

/** The beacon pool. Instance state, unlike everything above it: a beacon is a
 *  position in a loop rather than a fact about the field, and two of these
 *  graphics on one page would each need their own. Fixed length and reused for
 *  ever — a beacon that has finished is the same object with a new cell under it,
 *  so starting and ending one costs nothing. */
interface Beacon {
    /** The cell it stands on. */
    dot: number
    /** What its card says, picked with the cell. Held even when the cards are off,
     *  so a beacon that starts on the second group and finishes on the third has
     *  something to show rather than picking a symbol mid-flight. */
    pair: string
    /** ms into its own run: negative while it waits its turn, PARKED while the
     *  beacons are switched off. */
    at: number
}
/** Not running and not waiting to. Distinct from a negative `at`, which is a
 *  beacon counting down to its next run. */
const PARKED = Number.NEGATIVE_INFINITY
const beaconPool: Beacon[] = Array.from({ length: BEACON_COUNT }, () => ({
    dot: 0,
    pair: CARD_PAIRS[0],
    at: PARKED
}))

/** How long one run lasts, which is the same question as "is there a card on the
 *  end of it". Read every frame rather than stored, so a reader crossing from one
 *  group to the next changes what the lights already in the air are doing. */
function beaconLife() {
    return (
        BEACON_SPARK_MS +
        BEACON_CLIMB_MS +
        (loopingCards() ? CARD_HOLD_AT_ROOF_MS : 0) +
        BEACON_CATCH_MS +
        BEACON_FADE_MS
    )
}

function beaconRest(life: number) {
    return life * (BEACON_REST[0] + Math.random() * (BEACON_REST[1] - BEACON_REST[0]))
}

function beaconWake(b: Beacon) {
    b.dot = (Math.random() * field.count) | 0
    b.pair = CARD_PAIRS[(Math.random() * CARD_PAIRS.length) | 0]
}

/** Advance the pool. `delta` is the frame's own motion time, so the beacons stop
 *  with everything else when the piece is off screen and pick up where they were
 *  rather than jumping — same reasoning as `clockMs`.
 *
 *  Which cells they use is `Math.random`, and deliberately not the deterministic
 *  hash the rest of the file runs on. That hash exists so the FIELD is the same
 *  picture on every load; a beacon is not part of the picture, it is something
 *  passing through it, and a loop that plays the same lights in the
 *  same order every time is a loop the reader can see the end of. */
function stepBeacons(delta: number) {
    const life = beaconLife()

    // The destination, up or down. Not a beacon and not on any beacon's clock —
    // one transition, held for as long as the group is on stage.
    hubLit = Math.min(1, Math.max(0, hubLit + (delta / HUB_LIGHT_MS) * (loopingRoutes() ? 1 : -1)))

    for (const b of beaconPool) {
        if (b.at === PARKED) {
            if (!looping()) continue
            // Waking the pool. The first run is spread over a whole rest
            // period, or the entire pool leaves the map on the same frame.
            beaconWake(b)
            b.at = -Math.random() * life * BEACON_REST[1]
            continue
        }

        // Switched off. A beacon still counting down to its turn has nothing to
        // finish, so it parks here rather than launching a light two seconds into
        // the next group's copy; one already in the air is the only case worth
        // playing out, and it does that below.
        if (!looping() && b.at < 0) {
            b.at = PARKED
            continue
        }

        b.at += delta
        if (b.at < life) continue

        // Done. Another cell, or park it — it is the RESPAWN that the switch
        // stops, which is what lets a light in the air finish its run instead of
        // being cut off mid-climb.
        if (!looping()) {
            b.at = PARKED
            continue
        }
        beaconWake(b)
        b.at = -beaconRest(life)
    }
}

/** One beacon's frame, or null when there is nothing of it to draw.
 *
 *  `head` and `tail` are HEIGHTS above the cell in drawn px, not coordinates —
 *  the drawing turns them into a line. `lit` is how much of the cell's own colour
 *  has gone over to the beacon, and `fade` is the light going out at the end.
 *
 *  The two easings are the two halves of the gesture and are not interchangeable:
 *  the head leaves fast and decelerates into the roof (ease-out, so it arrives
 *  rather than stops), while the tail sets off gently and arrives gently
 *  (smoothstep), which is what makes the catch-up read as the trail being drawn
 *  in after the light rather than as a second light chasing it. */
function beaconState(at: number, show: number) {
    if (at < 0 || at >= beaconLife()) return null

    const spark = Math.min(1, at / BEACON_SPARK_MS)

    const climbMs = at - BEACON_SPARK_MS
    const u = Math.min(1, Math.max(0, climbMs / BEACON_CLIMB_MS))
    const head = BEACON_ROOF * (1 - (1 - u) ** 3)

    // `show` is the card's whole turn, inserted here — zero where there is no
    // card, so the light goes straight from arriving to being caught up.
    const catchMs = climbMs - BEACON_CLIMB_MS - show
    const c = Math.min(1, Math.max(0, catchMs / BEACON_CATCH_MS))
    const tail = BEACON_ROOF * c * c * (3 - 2 * c)

    const fadeMs = catchMs - BEACON_CATCH_MS
    const fade = 1 - Math.min(1, Math.max(0, fadeMs / BEACON_FADE_MS))

    // The cell holds its colour for as long as the trail is still standing on it,
    // and lets go as the trail lifts away.
    return { lit: spark * (1 - c), head, tail, fade }
}

/** And the card's own frame, measured from the moment the light stopped climbing.
 *  Null until there is one and after it has gone.
 *
 *  Each stage is a plain ramp against its own span and they do not overlap, which
 *  is what the three drawn states are: the bubble, then the container, then the
 *  letters. `chars` is a count rather than a fraction because a letter is either
 *  typed or it is not. */
function cardState(at: number) {
    // The lead: the card's own clock starts before the light gets there.
    const ms = at - BEACON_SPARK_MS - BEACON_CLIMB_MS + CARD_LEAD_MS
    if (ms < 0) return null

    const exit = Math.min(1, Math.max(0, (ms - CARD_SHOW_MS) / CARD_EXIT_MS))
    if (exit >= 1) return null

    const typeFrom = CARD_DOT_MS + CARD_BOX_MS

    return {
        dot: Math.min(1, ms / CARD_DOT_MS),
        box: Math.min(1, Math.max(0, (ms - CARD_DOT_MS) / CARD_BOX_MS)),
        // Ease-in-out on the pair, which is a curve on the SPEED of the typing:
        // the first letter or two arrive unhurried, the middle of the string goes
        // quickly, and the last letter settles instead of being cut off. Linear,
        // a six-letter string at this length reads as a machine emitting
        // characters at a fixed rate — true, and the wrong kind of true.
        typed: smoothstep(typeFrom, typeFrom + CARD_TYPE_MS, ms),
        // Ease-out on the lift, so it leaves the way the light arrived.
        lift: CARD_EXIT_LIFT * (1 - (1 - exit) ** 3),
        alpha: 1 - exit
    }
}

/** One route's frame, measured from the moment its card finished typing. Null
 *  before the money leaves and after it has gone.
 *
 *  `head` and `tail` are positions ALONG the arc, 0 at the card and 1 at the hub,
 *  which is the same shape as the lights: the tail sits at the card while the head
 *  runs (so the trail is the whole of the path taken, exactly as Figma draws it),
 *  and only then does the tail follow it home.
 *
 *  Ease-in-out on both, because this one is a journey rather than a launch — it
 *  leaves, it travels, it arrives. The lights use an ease-OUT for their climb,
 *  which is the shape of a thing thrown. */
function routeState(at: number) {
    const ms = at - BEACON_SPARK_MS - BEACON_CLIMB_MS + CARD_LEAD_MS - ROUTE_FROM_MS
    if (ms < 0) return null

    const fadeMs = ms - ROUTE_FLY_MS - ROUTE_CATCH_MS
    const fade = 1 - Math.min(1, Math.max(0, fadeMs / ROUTE_FADE_MS))
    if (fade <= 0) return null

    return {
        head: smoothstep(0, ROUTE_FLY_MS, ms),
        tail: smoothstep(ROUTE_FLY_MS, ROUTE_FLY_MS + ROUTE_CATCH_MS, ms),
        fade
    }
}

/** The pill, as a path. Always fully rounded — the radius IS half the height, so
 *  this is two arcs and two lines rather than a rounded rectangle with a corner
 *  radius that has to be clamped. At the 24-wide state the two arcs meet and it is
 *  a circle, which is what Figma's state 01 is. */
function pillPath(x: number, y: number, w: number, h: number) {
    const r = h / 2
    const path = new Path2D()
    path.moveTo(x + r, y)
    path.lineTo(x + w - r, y)
    path.arc(x + w - r, y + r, r, -Math.PI / 2, Math.PI / 2)
    path.lineTo(x + r, y + h)
    path.arc(x + r, y + r, r, Math.PI / 2, -Math.PI / 2)
    path.closePath()
    return path
}

// ------------------------------------------------------------------ renderer --
// Cells are batched by quantised ink: one Path2D per bucket, one fill per bucket.
// The alternative — set a fill style and fill per cell — is 3,447 state changes a
// frame. Twenty-four steps across a ramp whose two ends differ by 34 points of red
// is under three points a step, which is invisible on a 2px dot and turns the
// whole field into at most twenty-four fills.
//
// The trail does NOT get that treatment. Its ghosts need an alpha the ink ramp
// cannot carry, and under that alpha the ramp stops being worth carrying, so they
// are three flat fills — one per lag, in the crest's colour — rather than three
// more rows of buckets. See the note in `draw`.
//
// The departure stays outside all of it: it applies to every cell equally, so it
// is a factor on the alpha of each fill rather than an axis of its own.
const BUCKETS = 24

/** The ramp, resolved to fill strings once. Index b is ink `b / (BUCKETS - 1) * 2`
 *  — idle at 0, lit at the midpoint, crest at the top. */
const RAMP = (() => {
    const rgb = (hex: string) => [0, 2, 4].map((at) => parseInt(hex.slice(1 + at, 3 + at), 16))
    const stops = [rgb(IDLE_INK), rgb(LIT_INK), rgb(CREST_INK)]
    const out: string[] = []
    for (let b = 0; b < BUCKETS; b++) {
        const v = (b / (BUCKETS - 1)) * 2
        const lo = v <= 1 ? 0 : 1
        const u = v - lo
        const mix = (c: number) => Math.round(stops[lo][c] + (stops[lo + 1][c] - stops[lo][c]) * u)
        out.push(`rgb(${mix(0)}, ${mix(1)}, ${mix(2)})`)
    }
    return out
})()

let ctx: CanvasRenderingContext2D | null = null
let cssWidth = 0
let cssHeight = 0
let scale = 1
let rafId = 0
let lastFrame = 0
/** Ambient time, accumulated only while the piece is on screen and running — so
 *  scrolling away and back resumes the breathing instead of snapping it to a new
 *  phase. Same reasoning as the particle cluster's `motionMs`. */
let clockMs = 0
let onScreen = false
let reduced = false
let io: IntersectionObserver | null = null
let ro: ResizeObserver | null = null

function draw() {
    if (!ctx || cssWidth <= 0) return

    ctx.clearRect(0, 0, cssWidth, cssHeight)

    const t = Math.min(1, Math.max(0, props.t))
    const present = 1 - smoothstep(EXIT_FROM, EXIT_TO, t)
    if (present <= 0.01) return

    // The field is scaled by WIDTH against the drawn 760 frame, then centred in
    // whatever height the box has. At the drawn square this is pixel-exact to
    // Figma; at a shorter box it keeps the field's size and loses only air.
    const k = cssWidth / BOX
    const originX = FIELD_X * k
    const originY = (cssHeight - GLOBE_FIELD.height * k) / 2 + FIELD_BIAS_Y * k

    // The field, by ink bucket, and the trail: ONE path per lag, not a row of
    // buckets per lag. A ghost is drawn at two fifths of the alpha or less, which
    // flattens the ramp to nothing — the twenty-four inks are within a couple of
    // points of each other by the time they land on the ground — so bucketing the
    // ghosts would be three more rows of fills to carry a distinction that cannot
    // be seen. Three fills, one per lag, and the ink is a constant.
    const paths: (Path2D | null)[] = new Array(BUCKETS).fill(null)
    const trails: (Path2D | null)[] = new Array(TRAIL_STEPS + 1).fill(null)
    const wake = Math.min(1, Math.max(0, props.wake))
    const front = frontAt(wake)

    /** One cell into one path. Everything drawn goes through here — the cell and
     *  every ghost of it — so the moveTo below is written once. */
    const plot = (path: Path2D, i: number, cy: number, grow: number) => {
        const cx = originX + field.x[i] * k
        const rx = Math.max(0.35, field.rx[i] * grow * k)
        const ry = Math.max(0.35, field.ry[i] * grow * k)
        // The moveTo is not optional. `ellipse` on a path that already has a
        // subpath joins the two with a straight line, so a bucket of 200 cells
        // without it draws 199 hairlines across the map — which looks exactly like
        // a smear. Landing the pen on the arc's own start point (angle 0, i.e.
        // cx + rx) makes that joining line zero-length.
        path.moveTo(cx + rx, cy)
        path.ellipse(cx, cy, rx, ry, 0, 0, Math.PI * 2)
    }

    for (let i = 0; i < field.count; i++) {
        const state = dotState(i, front, clockMs)
        const bucket = Math.min(BUCKETS - 1, Math.max(0, Math.round((state.ink / 2) * (BUCKETS - 1))))
        plot(
            paths[bucket] || (paths[bucket] = new Path2D()),
            i,
            originY + (field.y[i] + state.dy) * k,
            state.scale
        )

        // The trail, and only where there is something to trail: a cell that is
        // not thrown has not moved, one the front has not reached has nothing
        // behind it, and one it left more than a trail ago has nothing left. Those
        // two comparisons are what keep the extra work on the front band instead
        // of on the field.
        if (!moves[i]) continue
        if (front <= wakeAt[i] - WAKE_EDGE) continue
        if (front - TRAIL_STEPS * TRAIL_LAG >= wakeAt[i] + WAKE_EDGE) continue

        for (let s = 1; s <= TRAIL_STEPS; s++) {
            const crest = crestOf(wokenAt(i, front - s * TRAIL_LAG))
            // Under a fiftieth of the throw the ghost is inside the cell it is
            // trailing, where all it would do is thicken a resting dot.
            if (crest < 0.02) continue
            plot(
                trails[s] || (trails[s] = new Path2D()),
                i,
                originY + (field.y[i] - JUMP * crest) * k,
                (1 + CREST_GROW * crest) * (1 - TRAIL_TAPER * s)
            )
        }
    }

    // Oldest ghost first, then the field over the top: a trail is behind the thing
    // making it. All three are the crest's own colour — a ghost is a copy of the
    // cell at its brightest — and the fade is entirely in the alpha.
    ctx.fillStyle = CREST_INK
    for (let s = TRAIL_STEPS; s >= 1; s--) {
        const path = trails[s]
        if (!path) continue
        ctx.globalAlpha = present * TRAIL_ALPHA * (1 - (s - 1) / TRAIL_STEPS)
        ctx.fill(path)
    }

    ctx.globalAlpha = present
    for (let b = 0; b < BUCKETS; b++) {
        const path = paths[b]
        if (!path) continue
        ctx.fillStyle = RAMP[b]
        ctx.fill(path)
    }

    // The beacons last, over everything: they are lights, and the field is what
    // they are leaving. A 2px line with round caps IS the drawn pill, so each one
    // is a stroke and a fill — a dozen or so of each at the busiest, against the
    // field's 3,447 cells, which is why they are drawn one at a time instead of
    // being batched into the machinery above.
    const show = loopingCards() ? CARD_HOLD_AT_ROOF_MS : 0
    ctx.lineCap = 'round'
    ctx.lineWidth = BEACON_WIDTH * k
    for (const beacon of beaconPool) {
        const state = beaconState(beacon.at, show)
        if (!state) continue

        const i = beacon.dot
        const x = originX + field.x[i] * k
        const foot = originY + field.y[i] * k

        if (state.lit > 0.01) {
            ctx.globalAlpha = present * state.lit
            ctx.fillStyle = BEACON_INK
            ctx.beginPath()
            ctx.ellipse(
                x,
                foot,
                Math.max(0.35, field.rx[i] * k),
                Math.max(0.35, field.ry[i] * k),
                0,
                0,
                Math.PI * 2
            )
            ctx.fill()
        }

        if (state.fade <= 0.01) continue
        const head = foot - state.head * k
        const tail = foot - state.tail * k
        // A gradient needs two places to run between, and at the end of the catch
        // there is only one — what is left there is the head itself.
        if (tail - head > 0.5) {
            const ramp = ctx.createLinearGradient(x, head, x, tail)
            ramp.addColorStop(0, BEACON_INK)
            ramp.addColorStop(1, BEACON_GONE)
            ctx.strokeStyle = ramp
        } else {
            ctx.strokeStyle = BEACON_INK
        }
        ctx.globalAlpha = present * state.fade
        ctx.beginPath()
        ctx.moveTo(x, head)
        ctx.lineTo(x, tail)
        ctx.stroke()
    }

    // The destination, under everything that arrives at it.
    if (hubLit > 0.01) {
        const hx = originX + field.x[hubDot] * k
        const hy = originY + field.y[hubDot] * k
        ctx.globalAlpha = present * hubLit
        ctx.fillStyle = HUB_RING_INK
        ctx.beginPath()
        ctx.arc(hx, hy, (field.rx[hubDot] + HUB_RING) * k, 0, Math.PI * 2)
        ctx.fill()
        ctx.fillStyle = ROUTE_INK
        ctx.beginPath()
        ctx.ellipse(
            hx,
            hy,
            Math.max(0.35, field.rx[hubDot] * k),
            Math.max(0.35, field.ry[hubDot] * k),
            0,
            0,
            Math.PI * 2
        )
        ctx.fill()
    }

    if (loopingCards()) drawCards(originX, originY, k, present)
    // Routes ride the destination's own light rather than the switch: leaving the
    // group takes the hub down over HUB_LIGHT_MS and the money still in the air
    // goes with it, instead of a dozen arcs being cut off mid-flight.
    if (hubLit > 0.01) drawRoutes(originX, originY, k, present * hubLit)

    ctx.globalAlpha = 1
}

/** The profit routes, last of all — over the cards, which is the order Figma
 *  draws them in (the route vectors are the animation frame's last children) and
 *  the right one: a route passes in FRONT of the trades it is not leaving from,
 *  so the eye follows it home instead of losing it under a pill.
 *
 *  `present` arrives already multiplied by the destination's own light, so this
 *  draws nothing the reader can see once the hub has gone dark. */
function drawRoutes(originX: number, originY: number, k: number, present: number) {
    if (!ctx) return

    const hx = field.x[hubDot]
    const hy = field.y[hubDot]
    ctx.lineCap = 'round'
    ctx.lineJoin = 'round'
    ctx.lineWidth = ROUTE_WIDTH * k

    for (const beacon of beaconPool) {
        const route = routeState(beacon.at)
        if (!route) continue

        // From the card's centre-top: its bottom sits on the light's roof, so its
        // top is one card higher again.
        const i = beacon.dot
        const x0 = field.x[i]
        const y0 = field.y[i] - BEACON_ROOF - CARD_H
        const dx = hx - x0
        const dy = hy - y0
        const chord = Math.hypot(dx, dy)
        // A card standing on the destination has nowhere to send anything.
        if (chord < 12) continue

        // The arc: one control point, straight up from the middle of the chord by
        // twice the apex height — a quadratic passes half way to its handle.
        const lift = Math.max(ROUTE_LIFT_MIN, ROUTE_LIFT_FRAC * chord)
        const cxDrawn = (x0 + hx) / 2
        const cyDrawn = (y0 + hy) / 2 - lift * 2

        // The piece of it that is currently lit, as its own quadratic: de
        // Casteljau at the tail, then at the head. Exact, and one curve to stroke
        // rather than a polyline to sample.
        const t0 = route.tail
        const t1 = route.head
        const qx = (t: number) =>
            (1 - t) * (1 - t) * x0 + 2 * (1 - t) * t * cxDrawn + t * t * hx
        const qy = (t: number) =>
            (1 - t) * (1 - t) * y0 + 2 * (1 - t) * t * cyDrawn + t * t * hy
        const ax = x0 + (cxDrawn - x0) * t0
        const ay = y0 + (cyDrawn - y0) * t0
        const bx = cxDrawn + (hx - cxDrawn) * t0
        const by = cyDrawn + (hy - cyDrawn) * t0

        const sx = originX + qx(t0) * k
        const sy = originY + qy(t0) * k
        const ex = originX + qx(t1) * k
        const ey = originY + qy(t1) * k
        const mx = originX + (ax + (bx - ax) * t1) * k
        const my = originY + (ay + (by - ay) * t1) * k

        // Transparent at the tail, full at the head — the gradient IS the trail,
        // and its axis is the straight line between the two ends, which is how
        // Figma's own is set up.
        if (Math.hypot(ex - sx, ey - sy) > 0.5) {
            const ramp = ctx.createLinearGradient(sx, sy, ex, ey)
            ramp.addColorStop(0, ROUTE_GONE)
            ramp.addColorStop(1, ROUTE_INK)
            ctx.strokeStyle = ramp
        } else {
            ctx.strokeStyle = ROUTE_INK
        }

        ctx.globalAlpha = present * route.fade
        ctx.beginPath()
        ctx.moveTo(sx, sy)
        ctx.quadraticCurveTo(mx, my, ex, ey)
        ctx.stroke()
    }
}

/** The trade cards, in a pass of their own after every light has been drawn.
 *
 *  Two reasons it is a second loop rather than the tail of the first: a card must
 *  sit over every beam and not just its own — one loop would let a later beam draw
 *  across an earlier card — and the text settings (font, tracking, baseline) are
 *  set once here instead of being restored around each stroke. */
function drawCards(originX: number, originY: number, k: number, present: number) {
    if (!ctx) return

    ctx.font = CARD_FONT_FACE.replace('%', String(CARD_FONT_PX * k))
    // Tracking is a recent addition to canvas; where it is missing the pair is a
    // hair tighter and, because the box is measured from the text, its pill comes
    // out a hair shorter with it. Nothing to guard.
    ctx.letterSpacing = `${CARD_TRACKING * k}px`
    ctx.textAlign = 'left'
    // Figma centres this type on its cap height (text-box-trim); canvas centres it
    // on the em box, which sits it a fraction lower. Under a pixel at 10px, and the
    // alternative is measuring cap height per frame.
    ctx.textBaseline = 'middle'
    ctx.lineWidth = CARD_STROKE_W * k

    for (const beacon of beaconPool) {
        const card = cardState(beacon.at)
        if (!card) continue

        const i = beacon.dot
        // The card's box, in drawn px: it grows with the text and is measured off
        // it, so the pill is the right size for whatever the font actually did.
        const text = beacon.pair.slice(0, Math.round(card.typed * beacon.pair.length))
        const textW = text ? ctx.measureText(text).width / k : 0
        const w = text ? CARD_PAD * 2 + CARD_BUBBLE + CARD_GAP + textW : CARD_PAD * 2 + CARD_BUBBLE

        // Centred on the beam, standing on its head, lifting as it leaves.
        const cx = originX + field.x[i] * k
        const bottom = originY + (field.y[i] - BEACON_ROOF - card.lift) * k
        const left = cx - (w / 2) * k
        const top = bottom - CARD_H * k

        const alpha = present * card.alpha

        // 2 — the container. Figma strokes it inside, so the path is inset by half
        // the stroke; drawn at the full box even while the text is still arriving,
        // which is what makes the growth read as the pill stretching.
        if (card.box > 0.01) {
            const inset = (CARD_STROKE_W * k) / 2
            const pill = pillPath(
                left + inset,
                top + inset,
                w * k - inset * 2,
                CARD_H * k - inset * 2
            )
            ctx.globalAlpha = alpha * card.box
            ctx.fillStyle = CARD_FILL
            ctx.fill(pill)
            ctx.strokeStyle = CARD_STROKE
            ctx.stroke(pill)
        }

        // 1 — the bubble, and the ring it sits in.
        const bx = left + (CARD_PAD + CARD_BUBBLE / 2) * k
        const by = top + (CARD_H / 2) * k
        ctx.globalAlpha = alpha * card.dot
        ctx.fillStyle = CARD_RING_INK
        ctx.beginPath()
        ctx.arc(bx, by, (CARD_BUBBLE / 2 + CARD_RING) * k, 0, Math.PI * 2)
        ctx.fill()
        ctx.fillStyle = CARD_BUBBLE_INK
        ctx.beginPath()
        ctx.arc(bx, by, (CARD_BUBBLE / 2) * k, 0, Math.PI * 2)
        ctx.fill()

        // 3 — the pair, as far as it has been typed. No fade on the letters: they
        // arrive, they do not appear.
        if (!text) continue
        ctx.globalAlpha = alpha
        ctx.fillStyle = CARD_TEXT_INK
        ctx.fillText(text, left + (CARD_PAD + CARD_BUBBLE + CARD_GAP) * k, by)
    }
}

function frame(now: number) {
    // Clamp the delta: a backgrounded tab hands back a multi-second gap on
    // return, which would jump the breathing and skip a beacon's whole run rather
    // than continue them.
    const delta = lastFrame ? Math.min(now - lastFrame, 64) : 0
    lastFrame = now
    clockMs += delta
    stepBeacons(delta)
    draw()
    rafId = requestAnimationFrame(frame)
}

function stop() {
    if (rafId) cancelAnimationFrame(rafId)
    rafId = 0
    lastFrame = 0
}

/** Run the ambient loop only when it can be seen and has not been paused.
 *  Everything else redraws on demand — see the props watcher. */
function sync() {
    if (onScreen && !props.paused && !reduced) {
        if (!rafId) rafId = requestAnimationFrame(frame)
    } else {
        stop()
    }
}

function resize() {
    const el = canvasRef.value
    const box = root.value
    if (!el || !box) return
    const rect = box.getBoundingClientRect()
    if (rect.width <= 0) return
    // Capped at 2: past that the extra pixels are invisible on a 2px dot and the
    // fill cost is real.
    const dpr = Math.min(2, window.devicePixelRatio || 1)
    cssWidth = rect.width
    cssHeight = rect.height
    scale = dpr
    el.width = Math.round(cssWidth * dpr)
    el.height = Math.round(cssHeight * dpr)
    el.style.width = `${cssWidth}px`
    el.style.height = `${cssHeight}px`
    ctx = el.getContext('2d')
    // One transform, so everything downstream works in CSS pixels.
    ctx?.setTransform(scale, 0, 0, scale, 0, 0)
    draw()
}

// The wave and the departure both move without the ambient loop's help — the
// first has its own clock, the second is the reader's scrolling — and when that
// loop is stopped (off screen, paused, or reduced motion) nothing else would
// repaint. While it IS running these are no-ops the next frame absorbs.
watch(
    () => [props.t, props.wake],
    () => {
        if (!rafId) draw()
    }
)
watch(() => props.paused, sync)

onMounted(() => {
    reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches
    resize()

    // Canvas text does not pull a webfont in the way a DOM node does, so ask for
    // the card's face by hand. Until it lands the cards would be drawn — and,
    // worse, MEASURED — in the fallback; the redraw is for the case where the
    // piece is sitting still when it arrives.
    document.fonts
        ?.load(CARD_FONT_FACE.replace('%', String(CARD_FONT_PX)))
        .then(() => {
            if (!rafId) draw()
        })
        .catch(() => {})

    ro = new ResizeObserver(resize)
    if (root.value) ro.observe(root.value)

    if (reduced) {
        // Resolved, once: the field lit and still. The section pins `wake` at 1
        // in this mode, so this draw is the end state.
        draw()
        return
    }

    io = new IntersectionObserver(
        (entries) => {
            for (const entry of entries) onScreen = entry.isIntersecting
            sync()
        },
        { rootMargin: '200px 0px' }
    )
    io.observe(root.value!)
})

onBeforeUnmount(() => {
    stop()
    io?.disconnect()
    ro?.disconnect()
    io = null
    ro = null
})
</script>

<template>
    <!-- Decoration over real copy: hidden from assistive tech outright. The
         argument it makes is made in words by the phrases beside it.
         `--globe-frame` is the box's aspect ratio, set by the section — the drawn
         760 square where there is room for it, shorter where there is not. -->
    <div
        ref="root"
        class="pointer-events-none relative w-full"
        style="aspect-ratio: var(--globe-frame, 1)"
        aria-hidden="true"
    >
        <canvas ref="canvasRef" class="absolute inset-0 block h-full w-full" />
    </div>
</template>
