// The dot field behind "module - The Solution" — a perspective-projected globe of
// 3447 land cells, from Figma "The_Solution" (3201:7987).
//
// GENERATED by scripts/extract-globe-dots.py. Do not hand-edit: re-export the node
// and re-run the script (its docstring has the two steps).
//
// Why the graphic arrives as data rather than as an asset: an SVG or a PNG of this
// map is one opaque object, and the brief is a field that ANIMATES — dots lighting
// up, drifting, arriving. As numbers, every dot is individually addressable and the
// whole field costs one canvas draw, so per-dot motion is free. See
// SolutionGlobe.vue, which is the only consumer.
//
// The blob is base-36, 8 chars per dot and no separators: centre x, centre y
// (both 3 chars), then width and height (1 char each), every value in tenths of
// a drawn pixel. 26 KB of string against 810 KB of the equivalent SVG — 18 KB over
// the wire, in its own chunk that arrives with the section — and it decodes in one
// pass into four typed arrays. See `decodeGlobeField`.

/** The drawn field's own box, in the coordinate space the values below are in.
 *  SolutionGlobe.vue places this inside the larger animation frame. */
export const GLOBE_FIELD = { width: 654.669, height: 259.895 } as const

/** Every cell is this one colour in the export — Tinted/700. The runtime lightens
 *  and dims from it rather than carrying a colour per dot. */
export const GLOBE_INK = '#51567A'

/** Tenths of a pixel per unit, i.e. what to divide a decoded value by. */
const UNIT = 10
const POS = 3
const SIZE = 1
const STRIDE = POS * 2 + SIZE * 2

const FIELD =
    '1a41zsyn18n1zvxn1g21yexn18o1yvxn1771yzxo1a71xrxo18q1xuxo1791xyxo1nh1vyxo1m01w0xo1kj1w3xo1bq1wmxo' +
    '1a91wpxo18s1wtxo17c1wwxo1m21uyxo1kl1v1xo1j41v4xp1bs1vkxp1ac1vnxp18v1vrxp17f1vuxp1bw1uhxp1af1ulxp' +
    '18z1uoxp17j1usxp4zn1wlvr4ya1wgvr4wx1wavr4vj1w5vr4u61vzvr1kp1swxp1dg1tbxp1bz1texp1aj1thxp1931tlxp' +
    '17n1toxp50k1vlur4z71vfvr4xv1vavr4wi1v4vr4v51uzvr4ts1uuvr4sf1upvr1ez1s4xq1dj1s7xq1c31saxq1an1sdxq' +
    '1971shxq17s1skxq51f1ukur5031ueur4yr1u9ur4xf1u4ur4w21tzur4uq1ttvr4td1tovr4s11tjvr4h21sivr1gj1qwxq' +
    '1f41r0xq1do1r3xq1c81r6wq1as1r9wq19c1rdwq17x1rgwq50x1tdur4zl1t8ur4ya1t3ur4wy1sxur4vm1ssur4ua1snur' +
    '4sy1siur4rm1sdur4q91s8ur4ox1s4vr4m71ruvr4ku1rqvr4jh1rlvr4i41rhvr4gq1rcvr1i41ppxq1go1pswq1f81pvwq' +
    '1dt1pywq1cd1q1wq1ax1q4wq19i1q8wq50e1s6ts4z41s1ts4xs1rwus4wh1rrur4v61rmur4tu1rhur4sj1rcur4r71r7ur' +
    '4pv1r2ur4oj1qxur4n61qtur4lu1qour4kh1qjvr4j41qfvr4hr1qbvr4ge1q6vr2u41nfxr1jo1ohwq1i81okwr1gt1omwr' +
    '1fd1oqwr1dy1otwq1ci1owwr1b31ozwr19o1p3wr4zv1qzts4yl1quts4xb1qpts4w01qkts4up1qfts4te1qaus4s31q5us' +
    '4qr1q0us4pg1pvur4o41prur4ms1pmur4lg1piur4k41pdur4ir1p9ur4hf1p4vr4g21p0vr4ep1owvr2yf1mbxr2wz1maxr' +
    '2vj1maxr2u31m9xr2sm1m9xr2r61m8xr1l81n8wr1jt1nbwr1id1newr1gy1nhwr1fj1nkwr1e41nnwr1cp1nqwr1b91ntwr' +
    '19v1nxwr18g1o0wr4zc1psts4ws1pits4vi1pcts4u81p8ts4sx1p3ts4rm1oyus4qb1otus4p01oous4np1okus4md1ofus' +
    '4l11obus4jq1o6us4ie1o2us4h11nyus4fp1ntus4ed1npur4d01nlvr2yd1l5xr2wx1l4xr2vh1l3xr2u11l3xr2sl1l3xr' +
    '1ld1m2wr1jy1m5wr1ij1m8wr1h41mbwr1fp1mewr1ea1mhwr1cv1mkwr1bg1mnwr1a21mrwr18n1muwr4wa1oats4v01o5ts' +
    '4tq1o0ts4sg1nvts4r51nqts4pu1nmts4ok1nhts4n91ndus4ly1n8us4km1n4us4jb1mzus4hz1mvus4gn1mrus4fc1mmus' +
    '4dz1mius44j1lsvs2zq1jzwr2ya1jyws2wu1jywr2vf1jxwr2tz1jwwr2sj1jwwr2r31jwxr2po1jwxr1mx1ktwr1li1kwwr' +
    '1k31kywr1io1l1wr1ha1l4wr1fv1l7wr1eg1lawr1d21lewr1bn1lhwr1a91lkwr18v1lowr4x01n7ss4vq1n2ss4uh1mxts' +
    '4t71msts4ry1mots4qo1mjts4pe1mets4o31mats4mt1m5ts4li1m0ts4k71lwus4iw1lsus4hl1lnus4g91ljus4ey1lfus' +
    '4471kkvs3861izws2zn1isws2y71irws2ws1iqws2vc1iqws2tx1ipws2sh1ipws2r21ipws2pm1ipws1oh1jkws1n31jmws' +
    '1lo1jpws1k91jrws1iv1juws1hg1jxws1g21k0ws1en1k3ws1d91k6ws1bv1kavs1ah1kdvs1931khvs4ty1lpss4sp1lkts' +
    '4rf1lgts4q61lbts4ow1l6ts4nm1l2ts4mc1kxts4l21ktts4jr1kots4ig1kkts4h51kgts4581jgus43w1jdvs42j1j9vs' +
    '39g1htws3821hrws30z1hlws2zk1hkws2y51hkws2wp1hjws2va1hiws2tv1hiws2sg1hiws2r01hhws2pl1hhws1rg1i8ws' +
    '1q11iaws1on1icws1n81ifws1lu1ihws1kg1ikws1j11inws1hn1iqws1g91itvs1ev1iwws1dh1izvs1c31j2vs1ap1j6vs' +
    '17y1jdvs4te1khss4s51kcss4pn1k3ts4oe1jyts4n41juts4lv1jpts4kl1jlts4jb1jgts4e41izus4a71inus48v1ikus' +
    '47j1igus4681icus44w1i8us39b1glws37x1gjws32a1gfws30v1gews2zg1gdws2y11gcws2wn1gbws2v81gbws2tt1gaws' +
    '2se1gaws2qz1gaws2pk1g9ws2o41g9ws1rl1h0ws1q71h2ws1ot1h5ws1ne1h7ws1m01haws1km1hdws1j81hfvs1hu1hivs' +
    '1gg1hlvs1f31hovs1dp1hsvs1cb1hvvs1ay1hyvs19k1i2vs1871i5vs16u1i9vs4rm1j4ss4p51ivss4nw1iqss4mm1ilts' +
    '4ld1ihts4dp1hrts48h1hbus4761h8us45u1h4us44j1h0us4371gxus40j1gqus3961fdws37r1fbws3261f6ws30r1f5ws' +
    '2zd1f4ws2xy1f4ws2wk1f3ws2v51f3ws2tq1f2ws2sc1f2ws2qx1f1ws2pi1f1ws2o31f1ws1rr1fsvs1qd1fuws1oz1fxvs' +
    '1nl1fzvs1m71g2vs1kt1g5vs1jf1g7vs1i21gavs1go1gdvs1fb1ggvs1dx1gkvs1ck1gnvs1b71gqvs19u1guvs18h1gxvs' +
    '1741h1vs15s1h4vs4zh1iurt4vw1ifrt4sa1i0st4r21hwst4d91gjtt42u1fout02b113mt01c11amt00e11glt0600zbmt' +
    '0510zimt0420zomt0340zumt06t0y2mt05u0y8mt04w0yfmt03x0yllt0300yslt0140z5lt03t0xjlt3901e4vt37m1e3vs' +
    '34u1e0vt33g1dzvt3221dyws30n1dxwt2z91dwwt2xv1dvws2wh1dvwt2v21duwt2to1duws2s91dtwt2qv1dtwt2ph1dtws' +
    '2o21dtwt1rx1ejvs1qj1emvt1p51eovs1nr1ervs1me1etvs1l01ewvs1jn1ezvs1i91f2vs1gw1f5vt1fj1f8vt1e61fbvs' +
    '1ct1ffvs1bg1fivs1a41flvs18r1fpvs17f1ftus1621fwut14q1g0us4wh1hbrt4u41h1rt4sw1gwrt4rp1gsrt4qi1gnrt' +
    '4pa1gist4o21gdst4fc1fitt48z1eytt47o1eutt3a71cxvt33b1cqvt31x1cpvt30j1covt2z51cnvt2xr1cnvt2wd1cmvt' +
    '2uz1clvt2tl1clvt2s71ckwt2qt1ckvt2pf1ckvt1tg1d9vt1s31dbvt1qp1ddvt1pc1dgvt1ny1divt1ml1dlvt1l81dovt' +
    '1jv1dqvt1ii1dtvt1h51dwvt1fs1e0vt1ef1e3vt1d31e6vt1bq1e9ut1ae1edut1921egut17q1ekut16e1eout1521esut' +
    '4vu1g2qt4sb1fnrt4r41fjrt4px1fert4op1f9rt4ni1f4st49t1dttt48j1dptt45z1dhtt43e1datt34k1bivt3361bhvt' +
    '31t1bgvt30f1bfvt2z11bevt2xo1bevt2wa1bdvt2ux1bcvt2tj1bcvt2s51bcvt2qr1bbvt2pd1bbvt1uz1bxvt1tm1c0vt' +
    '1s91c2vt1qw1c4vt1pj1c7vt1o51c9vt1mt1ccvt1lg1cfvt1k31civt1iq1clvt1he1covt1g11crut1ep1cuut1dd1cxut' +
    '1c11d0ut1ap1d4ut19d1d8ut1811dbut16p1dfut15e1djut4v71etqt4o51e0rt4mx1dvrt4ja1dist4i21ddst4ed1d0st' +
    '4bv1csst3311a8vt31o1a7vt30b1a6vt2yy1a5vt2xk1a4vt2w71a4vt2uu1a3vt2tg1a3vt2s31a2vt2qp1a2vt2pc1a2vt' +
    '1ts1arvt1sf1atvt1r21avvt1pq1ayvt1od1b0vt1n11b3vt1lo1b6ut1kc1b8ut1iz1bbut1hn1beut1gb1biut1ez1blut' +
    '1dn1bout1cb1bsut1b01bvut19o1byut18d1c2ut1711c6ut15q1caut14f1ceut4jy1cdrt4f31bvst4dv1brst4cm1bnst' +
    '4be1bjst4a51best48w1bast47n1b6st46d1b3tt4541aztt42k1astt32w18zvt31j18yvt30618xvt2yt18wvt2xg18vvt' +
    '2w318uvt2uq18uvt2td18tvt2s018tvt2qn18tvt2pa18tvt2nx18svt1tz19hut1sm19jut1ra19mut1px19out1ol19rut' +
    '1n919uut1lx19wut1kk19zut1j91a2ut1hx1a5ut1gl1a8ut1f91acut1dy1afut1cm1aiut1bb1amut1a01aput18p1atut' +
    '17e1axtt1631b0tt4fs1aqrt4c41adst4aw1a9st49o1a5st48f1a1st47619xst44o19qst43f19mtt42519itt32r17put' +
    '31e17out30217nut2yp17mvt2xd17lvt2w017lut2un17kvt2tb17kvt2ry17jvt2ql17jvt2p817jvt2nw17jvt2mj17jvt' +
    '1ot18hut1nh18kut1m518nut1ku18qut1ji18tut1i718wut1gv18zut1fk192ut1e9195ut1cy199ut1bn19ctt1ac19gtt' +
    '19119ktt17r19ntt16g19rtt4bm194st4ae190st49618vst47y18rst46p18nst42z18cst41q188st40g185tt33x16gut' +
    '32l16fut31916eut2zx16dut2yl16cut2x816cut2vw16but2uk16aut2t816aut2rv16aut2qj169ut2p7169ut2nu169ut' +
    '2mi169ut2l5169ut1nq17aut1me17dut1l317gut1js17jut1ih17mut1h617put1fv17sut1ek17wtt1d917ztt1bz183tt' +
    '1ao186tt19e18att18418ett4ep187rt4b317urt49v17qrt42i172st41a16zst353158ut33r156ut32f155uu314154uu' +
    '2zs153ut2yg152ut2x4152ut2vt151ut2uh150uu2t5150ut2rt150ut2qh14zut2p514zuu2nt14zut2mh14zuu1ld166tt' +
    '1k2169tt1ir16ctt1hg16ftt1g616jtt1ew16mtt1dl16ptt1cb16ttt1b116xtt19r170tt18h174tt177178tt14o17gst' +
    '4u418spt4t018npt4rw18ipt4l417pqt4e416xrt4cy16trt4ak16krt42215sst40t15pst3zl15lst37i140uu36713ztt' +
    '34w13yut33l13wuu32a13vut30y13uuu2zn13tuu2yc13suu2x013sut2vp13ruu2ud13qut2t213quu2rq13quu2qf13puu' +
    '2p313put2nr13puu2mg13put2l413puu1kc14ztt1j2152tu1hs156tt1gh159tt1f715ctt1dx15gtt1co15jtt1be15ntt' +
    '1a415qtt18v15ust153166st12m16est4vk17tot4uh17oot4te17jpt4sb17ept4r7179pt4q4174pt4nv16upt4i7165qt' +
    '4h1161qt4fw15wqt4eq15sqt4dk15nqt41l14ist40d14fst37b12qtu36012ptu34p12otu33f12mtu32412ltu30t12ktu' +
    '2zi12jtu2y712itu2ww12huu2vl12huu2ua12guu2sz12guu2ro12fuu2qc12fuu2p112fuu2nq12fuu2mf12fuu2l312fut' +
    '2js12fuu2fu12huu2ej12huu2bx12juu1gt13ztt1fk142tt1ea146tt1d1149st1br14dst1ai14gsu19914kst132154st' +
    '4ts16eot4sp169ot4qj15zpt4gg14rqt4fa14mqt4cz14dqt4bt149qt44q13kru43i13grt42b13cru3zw135st3q212est' +
    '37311gtu35t11ftu34i11dtu33811ctu31y11btu30n11atu2zd119tu2y2118tu2ws117tu2vh117tu2u6116tu2sw116tu' +
    '2rl115tu2qa115tu2oz115tu2no115tu2me115tu2l3115tu2js115tu2ih116tu2h6116tu2fv117tu2el117tu2da118tu' +
    '2bz119tu2ao11atu29d11btu14q13qst13i13ust12a13zst112143rt0zv148rt0yn14crt4t2155ot4rz150ot4qw14uot' +
    '4pt14ppt4gy13mqt4eo13cqu4ce133qt4b812zqt44712art430126ru41t122ru3zf11vru3og111su3n710ysu39e109tu' +
    '385108tu36v106tu35l105tu34c103tu332102tu31s101tu30i100tu2z70zztu2xx0zytu2wn0zxtu2vd0zwtu2u30zwtu' +
    '2ss0zvtu2ri0zvtu2q80zvtu2ox0zutu2nn0zutu2md0zutu2l20zvtu2js0zvtu2ih0zvtu2h70zwtu2fx0zwtu2em0zxtu' +
    '2dc0zytu2c10zztu2ar100tu29h101tu286102tu26w103tu20h10btu1vd10ktu16e12cst13y12krt12r12prt11j12tru' +
    '10c12yrt0z5132ru0xy137rt0ws13brt0vl13grt0ue13lrt0t813qrt4yj14snt4wi14hnt4hg12gpt4gb12cpt4f7127pt' +
    '4an11pqt43o110ru42i10wrt41b10sru40410oru3yy10kru3o20zrsu3mu0zosu3lm0zlsu35e0yutu3440yttu32v0ystu' +
    '31l0yqtu30c0yptu2z20yotu2xs0yntu2wj0yntu2v90ymtu2tz0ymtu2sp0yltu2rf0yltu2q50yktu2ov0yktu2nl0yktu' +
    '2mc0yktu2l10yktu2js0yltu2ii0yltu2h80yltu2fy0ymtu2eo0yntu2de0yntu2c40yotu2au0yqtu29k0yqtu28a0ystu' +
    '2700yttu1y40z5tu1wv0z7su1e510fsu1bp10msu1ah10qsu19910ust16u112ru13811frt12111jru0xb121ru0w4126qt' +
    '0uy12bqt0ts12gqu50r13zmt4zs13tmt4yr13ont4xr13int4wr13cnt4vq137nt4up132nt4qj12got4ph12bot4nc120ot' +
    '4m911vot4gs116pt4fo112pt4cb10oqu4a210fqt41z0zmqt40t0ziru3zn0zeru3yg0zart3x90z7ru3w30z3ru3no0yhru' +
    '3mg0yesu38x0xpsu37o0xnsu36f0xmsu3560xksu33x0xjsu32o0xhsu31f0xgsu3060xfsu2yx0xesu2xn0xdtu2we0xcsu' +
    '2v50xctu2tv0xbtu2sm0xbtu2rc0xatu2q30xatu2ot0xatu2nk0xatu2ma0xatu2l10xatu2jr0xatu2ii0xbtu2h80xbtu' +
    '2fz0xctu2ep0xdtu2dg0xdtu2c60xetu2ax0xftu29n0xgtu28e0xitu2740xjtu1gz0yysu1fr0z1su1c30zcru1aw0zgru' +
    '18h0zoru1630zwrt11c10drt0xu10rqu0wo10wqt0vi111qu0ud116qt0qx11lqt4yz12kmt4xz12emt4wz129nt4vz123nt' +
    '4uy11xnt4ty11snt4sx11mnt4rw11hnt4qu11cot4mn10rot4f10zspt44x0yoqu43r0ykqu41g0ycqu40a0y8qu3z40y4qu' +
    '3xy0y0qu3ws0xxru3vm0xtru3po0xdru3oh0xaru3na0x7ru3m20x4ru3kv0x1ru3b40wisu39w0wgsu38o0wfsu37f0wdsu' +
    '3670wbsu34y0wasu33q0w8su32h0w7su3190w6su3000w5su2yr0w4su2xi0w3su2w90w2su2v00w2su2tr0w1su2sj0w0su' +
    '2ra0w0su2q10w0su2os0w0su2ni0w0su2m90w0su2l00w0su2jr0w0su2ii0w1su2h90w1su2g00w2su2er0w2su2di0w3su' +
    '2c90w4su2b00w5su29r0w6su28i0w7su2790w9su1ut0wrsu1tl0wusu18y0yeru17r0yiru16k0ymrt0yd0zhqt0x80zmqt' +
    '0w30zrqt0ux0zwqt0ts101qt0sn106qt4y611amt4w710znt4v710unt4u710ont4t610int4s510dnt4r4107nt4q3102nt' +
    '4p20zxot4o00zrot4mz0zmot4kv0zcot4c70y8pu4b30y4pu49z0xzpu48u0xvpt45h0xipu44c0xeqt4370x9qu4220x5qt' +
    '40x0x1qu3zs0wyqu3ym0wuqu3xg0wqqu3wa0wmqu3v40wjqu3ty0wfqt3ss0wcrt3qf0w6ru3p90w2ru3o20vzru3mv0vwru' +
    '3lo0vuru3ki0vrru3ja0voru3c20vart3au0v8su39m0v6su38e0v5su3760v3su35y0v1su34q0v0su33i0uysu32a0uxsu' +
    '3120uwsu2zu0uvsu2yl0uusu2xd0utsu2w50ussu2uw0ussu2to0ursu2sf0uqsu2r70uqsu2py0uqsu2op0uqsu2nh0uqsu' +
    '2m80uqsu2l00uqsu2jr0uqsu2ii0uqsu2ha0ursu2g10ussu2et0ussu2dk0utst2cb0uusu2b30uvsu29u0uwsu28m0uxsu' +
    '27d0uzsu1k40w7ru1ix0waru1hq0wdru1gi0whru19e0x4ru1880x8ru1710xcrt0yx0y7qt0xs0ycqt0wn0yhqt0vi0ymqt' +
    '0ue0yrpt0t90ywpt0s50z1pt0px0zcpt4ve0zqmt4uf0zkmt4tf0zent4se0z9nt4re0z3nt4qd0yynt4pd0ysnt4ob0ynnt' +
    '4na0yhnt4m90ycot4l70y7ot4j30xxot4890wlpt4750wgpt4610wcpt44w0w8pu43s0w4pt42n0vzqu41i0vvqt40e0vrqt' +
    '3z80voqt3y30vkqu3wy0vgqu3vt0vcqt3un0v9qt3th0v5qu3sc0v2qu3r60uzqu3q00uwqt3ot0usqu3nn0upru3mh0umru' +
    '3la0ujru3k40uhru3ix0ueru3br0u0rt3ak0tyrt39d0twrt3850turu36y0ttru35q0trru34i0tqru33b0tosu3230tnst' +
    '30v0tmsu2zo0tlsu2yg0tkst2x80tjsu2w00tisu2us0thst2tk0thsu2sc0tgsu2r40tgst2pw0tgsu2on0tgsu2nf0tgst' +
    '2m70tgsu2kz0tgsu2jr0tgst2ij0tgsu2hb0thst2g20tist2eu0tisu2dm0tjsu2ce0tkst2b60tlst29y0tmst28q0tnst' +
    '27i0tost2060tzsu1yy0u1su1wj0u5su1vb0u7ru1lo0utrt1kh0uxrt1ja0v0rt1i30v3ru18o0vyqt17j0w2qu11r0woqt' +
    '10m0wtqt0zh0wxqt0yd0x2qt0x80x7qu0w30xcpt0uz0xhpt0tv0xmpt0sr0xrpt0rn0xxpt0qj0y2pt4vl0ymmt4um0ygmt' +
    '4tm0yamt4sm0y5nt4rn0xznt4nl0xdnt4mk0x8nt4li0x2nt4kh0wxot4jg0wsot4ie0wnot47m0vbpt46j0v6pt45f0v2pu' +
    '44b0uypt4370uupt4230uqpt40y0ulpu3zu0uhpt3yp0ueqt3xl0uaqt3wg0u6qu3vb0u2qt3u50tzqt3t00tvqt3rv0tsqu' +
    '3qp0tpqt3pk0tmqt3oe0tiqt3n80tfqt3m20tcqt3kw0taqt3jq0t7ru3ik0t4rt3hd0t2rt3g70szrt3aa0sort3930smrt' +
    '37w0skrt36p0sjrt35i0shrt34a0sgrt3330sert31w0sdrt30p0scrt2zh0sbrt2ya0sart2x20s9rt2vv0s8rt2un0s8rt' +
    '2tg0s7rt2s80s6rt2r10s6rt2pt0s6rt2om0s6st2ne0s6rt2m60s6st2ky0s6rt2jr0s6st2ij0s6rt2hb0s7st2g40s8rt' +
    '2ew0s8st2do0s9rt2ch0sart2b90sbrt2a10scrt28u0sdrt1m10tkrt1ku0tnrt1ih0ttrt1800usqt16v0uwqu15q0v0qt' +
    '14l0v5qt13g0vaqt12b0veqt1160vjqt1020vnpt0yx0vspt0xt0vxpt0wp0w2pt0vl0w7pt0uh0wcpt0td0whpt0sa0wnpt' +
    '0r60wspt0q30wxpt0p00x3ot0nx0x8ot4su0x1mt4ru0wvmt4mu0w3nt4lt0vynt4ks0vtnt4jr0vnnt4iq0vint4ho0vdot' +
    '4ce0uoot4700u1pt45x0txpt44u0tspt43q0topt42m0tkpt41i0tgpt40e0tcpt3za0t8pt3y60t4pt3x10t0pt3vx0swpt' +
    '3us0sspt3to0spqt3sj0smqt3re0siqt3q90sfqt3p30scqt3ny0s8qt3mt0s5qt3ln0s2qt3ki0s0qt3jc0rxqt3i60ruqt' +
    '3h00rsqt3fu0rpqt3eo0rnrt3di0rlqt3cc0rirt3b50rgrt39z0rert36g0r9rt3590r7rt3420r6rt32w0r5rt31p0r3rt' +
    '30i0r2rt2zb0r1rt2y40r0rt2wx0qzrt2vq0qyrt2uj0qyrt2tc0qxrt2s50qxrt2qy0qwrt2pr0qwrt2oj0qwrt2nc0qwrt' +
    '2m50qwrt2ky0qwrt2jr0qwrt2ij0qxrt2hc0qxrt2g50qyrt2ey0qyrt2dr0qzrt2cj0r0rt2bc0r1rt2a50r2rt19n0teqt' +
    '18i0tiqt17d0tmqt1680trqt1540tvqt13z0u0pt12v0u4pt11q0u9pt10m0uept0zi0uipt0ye0unpt0xa0uspt0w70uxpt' +
    '0v30v2pt0u00v8pt0sx0vdpt0ru0viot0qr0voot0po0vtot0om0vzot4m30uunt4l20uont4k20ujnt4j10uent4i00u9nt' +
    '4gy0u3nt4fx0tynt4ew0ttot4du0toot4cs0tjot4bq0teot46e0srot45b0snpt4480sipt4340sept4210sapt40y0s6pt' +
    '3zu0s2pt3yq0rypt3xm0rupt3wi0rqpt3ve0rmpt3ua0rjpt3t60rfpt3s10rcqt3qx0r8qt3ps0r5qt3on0r2qt3ni0qzqt' +
    '3md0qwqt3l80qtqt3k30qqqt3iy0qnqt3hs0qkqt3gn0qiqt3fh0qgqt3ec0qdqt3d60qbqt3c00q9qt3au0q7qt39o0q5qt' +
    '38i0q3qt37c0q1qt3500pyqt33u0pwqt32o0pvrt31h0purt30b0psrt2z50prrt2xy0pqrt2ws0pqrt2vl0pprt2uf0port' +
    '2t80port2s10pnrt2qv0pnrt2po0pmrt2oh0pmrt2nb0pmrt2m40pmrt2kx0pmrt2jr0pnrt2ik0pnrt2hd0port2g60port' +
    '2ez0pprt2dt0pqrt2cm0pqrt2bf0psrt2a90psrt1b90s0qt1a50s4qt1900s8qt17v0sdpt16r0shpt15n0slpt14j0sqpt' +
    '13e0supt12a0szpt1170t4pt1030t9pt0yz0tept0xw0tjpt0wt0topt0vq0ttpt0un0tyot0tk0u3ot0sh0u8ot0rf0ueot' +
    '0qc0ujot0pa0upot0o80uuot0n60v0ot4mb0tqnt4lb0tknt4kb0tfnt4jb0tant4ha0sznt4f80spnt4e60sknt4c30saot' +
    '4a00s0ot48y0rvot46u0rmot45r0rhot44p0rdot43m0r9ot42j0r4ot41g0r0pt40d0qwpt3za0qspt3y60qopt3x30qkpt' +
    '3vz0qgpt3uv0qdpt3ts0q9pt3so0q6pt3rk0q2pt3qf0pzpt3pb0pvpt3o70pspt3n20pppt3ly0pmqt3kt0pjqt3jo0pgqt' +
    '3ij0peqt3hf0pbqt3g90p8qt3f40p6qt3dz0p4qt3cu0p1qt3bp0ozqt3aj0oxqt39e0ovqt3880otqt3730orqt35x0oqqt' +
    '34r0ooqt33m0onqt32g0olqt31a0okqt3040ojqt2yy0oiqt2xs0ohqt2wm0ogqt2ua0ofqt2t40oeqt2ry0oert2qs0odqt' +
    '2n90odrt2m30odqt2kx0odrt2jq0odrt2ik0oeqt2he0oert2g80ofqt2f10ofrt2dv0ogrt2cp0ohrt2bj0oirt1br0qqpt' +
    '1an0qupt19i0qzpt18e0r3pt17a0r7pt1660rcpt1520rgpt13z0rlpt12v0rppt11s0rupt10o0rzpt0zl0s4pt0yi0s9pt' +
    '0xf0sept0wc0sjot0va0soot0u70stot0t50szot0s20t4ot0r00taot0py0tfot0ox0tlot0nv0tqot4oi0sxmt4fj0rknt' +
    '48a0qmot4540q8ot4420q4ot4300pzot41x0pvot40v0prot3zs0pnot3yp0pjot3xm0pfot3wj0pbpt3vg0p7pt3uc0p3pt' +
    '3t90p0pt3s50owpt3r20otpt3py0oppt3ou0ompt3nq0ojpt3mm0ogpt3li0odpt3ke0oapt3j90o7pt3i50o4pt3h10o2pt' +
    '3fw0nzqt3er0nxqt3dn0nuqt3ci0nsqt3bd0nqqt3a80noqt3930nmqt37y0nkqt36t0niqt35o0ngqt34j0nfqt33d0ndqt' +
    '3280ncqt3130nbqt2zx0naqt2ys0n9qt2kw0n4qt2jq0n4qt2ik0n4qt2hf0n5qt2g90n5qt2f30n6qt2dy0n7qt2cs0n8qt' +
    '1c80phpt1b40plpt1a00pppt18x0ptpt17t0pypt16q0q2pt15m0q7pt14j0qbpt13g0qgpt12d0qlot11a0qppt1070quot' +
    '0z40qzot0y10r4ot0wz0raot0vx0rfot0uu0rkot0ts0rpot0sq0rvot0rp0s0ot0qn0s6ot0pm0sbot07o0vdlt4it0qwmt' +
    '4ft0qgnt48o0phnt47m0pcnt46l0p8ot45j0p3ot44h0ozot43g0ouot42e0oqot41b0omot4090ohot3z70odot3y40o9ot' +
    '3x20o5ot3vz0o1ot3uw0nyot3tt0nuot3sq0nqpt3rn0nnpt3qk0njpt3pg0ngpt3od0ndpt3na0napt3m60n6pt3l20n4pt' +
    '3jy0n1pt3iu0mypt3hr0mvpt3gn0mspt3fi0mqpt3ee0mnpt3da0mlpt3c60mjpt3b10mhpt39x0mfpt38s0mdqt37o0mbqt' +
    '36j0m9qt35e0m7qt34a0m6qt3350m4qt3200m3qt30v0m2qt2zq0m1qt2yl0m0qt2xg0lzqt2v60lxqt2sw0lwqt2kv0lvqt' +
    '2jq0lvqt2il0lvqt2hg0lwqt2ga0lwqt1h50nspt1g10nwpt1ex0o0pt1du0o4pt1cq0o8pt1bm0ocpt1aj0ogpt19g0okpt' +
    '18c0oopt1790otpt1660oxpt1530p2ot1400p6ot12y0pbot11v0pgot10t0plot0zq0pqot0yo0pvot0xm0q0ot0wk0q5ot' +
    '0vi0qaot0ug0qgot0tf0qlot0sd0qrnt0rc0qwnt0qb0r2nt0pa0r8nt0o90rdnt08i0u4lt4k10pxmt4j10psmt4f30p6nt' +
    '4b20omnt47z0o8nt46y0o3nt45x0nynt44w0nunt43u0npot42t0nlot41r0nhot40p0ncot3zo0n8ot3ym0n4ot3xj0n0ot' +
    '3wh0mwot3vf0msot3ud0moot3ta0mlot3s70mhot3r50meot3q20maot3oz0m7ot3nw0m4pt3mt0m1pt3lq0lxpt3km0lupt' +
    '3jj0lspt3ig0lppt3hc0lmpt3g80lkpt3f50lhpt3e10lfpt3cx0lcpt3bt0lapt3ap0l8pt39l0l6pt38h0l4pt37d0l2pt' +
    '3690l0pt3550kzpt3410kxpt32w0kwpt31s0kupt30o0ktpt2zj0kspt2yf0krpt2xa0kqqt2w60kpqt2v10koqt2rn0kmqt' +
    '2qi0kmqt2m00kmqt2f70koqt2e20kpqt2cx0kqqt2bt0krqt1fe0mrpt1eb0mupt1d80mypt1c50n2pt1b20n7ot19y0nbot' +
    '18w0nfot17t0nkot16q0noot15o0ntot14l0nxot13j0o2ot12h0o7ot11e0ocot10c0ohot0zb0omot0y90orot0x70owot' +
    '0w60p1ot0v40p6nt0u30pcnt0t20phnt0s10pnnt0r00psnt0pz0pynt0oz0q4nt0b70silt09b0svlt06i0tflt4l60ozmt' +
    '4bc0nint4ac0ndnt49c0n8nt48b0n3nt47b0mznt46a0munt4590mpnt4480mlnt4370mgnt4260mcnt4150m8ot4030m3ot' +
    '3z20lzot3y00lvot3wz0lrot3vx0lnot3uv0ljot3tt0lgot3sr0lcot3ro0l8ot3qm0l5ot3pk0l1ot3oh0kyot3nf0kvot' +
    '3mc0ksot3l90kpot3k60kmot3j30kjot3i00kgps3gx0kdpt3fu0kbpt3er0k8pt3do0k6ps3ck0k4pt3bh0k1pt3ae0jzps' +
    '39a0jxps3860jvps3730jtps35z0jsps34v0jqps33s0jpps32o0jnps31k0jmps30g0jkps2zc0jjps2y80jips2x40jhps' +
    '2w00jhps2uw0jgps2ts0jfps2so0jfps2rk0jeps2qf0jeps2o70jdps2n30jdps2gd0jfps2f90jgps2e50jhps2d00jips' +
    '2bw0jjps1lb0l0pt1k80l3pt1j40l7pt1i10lapt1gy0lept1fv0liot1es0lmot1dq0lqot1cn0luot1bk0lyot1ai0m2ot' +
    '19f0m6ot18d0maot17a0mfot1680mkot1560moot1440mtot1320myot1210n3ot10z0n7ot0zx0ncot0yw0niot0xv0nnnt' +
    '0wt0nsnt0vs0nxnt0ur0o3nt0tq0o8nt0sq0oent0rp0ojnt0qp0opnt0po0ovnt0oo0p0nt0no0p6nt0mo0pcmt0c00r9lt' +
    '0b20rflt0a40rmlt0970rtlt0890rzlt07c0s6lt06f0sdlt4n90o7lt4el0mtmt4dm0momt4cm0mjmt4bm0memt4an0m9mt' +
    '49n0m4mt48n0lznt47n0lunt46m0lqnt45m0llnt44l0lgnt43l0lcnt42k0l7nt41j0l3nt40i0kznt3zh0kvnt3yg0kqnt' +
    '3xf0kmnt3we0kint3vc0keot3ub0kbot3t90k7os3s70k3os3r50k0ot3q40jwos3p20jtos3nz0jqos3mx0jmos3lv0jjos' +
    '3kt0jgos3jq0jdos3io0jaos3hl0j8os3gj0j5os3fg0j2os3ed0j0os3da0iyos3c80ivos3b50itos3a20iros38z0ipos' +
    '37w0inps36s0ilps35p0ikps34m0iips33j0igps32f0ifps31c0ieps3080icps2z50ibps2y10iaps2wy0i9ps2vu0i8ps' +
    '2ur0i8ps2tn0i7ps2sk0i6ps2rg0i6ps2qc0i6ps2o50i5ps2lx0i5ps2ku0i5ps2im0i6ps2gf0i7ps2fb0i8ps1oz0jios' +
    '1nw0jlos1lq0jros1ii0k2ot1hf0k5os1gc0k9ot1fa0kdos1e80khos1d50klot1c30kpot1b10ktot19z0kyot18x0l2ot' +
    '17v0l6ot16t0lbot15r0lfot14q0lkot13o0lpot12n0lunt11l0lznt10k0m4nt0zj0m9nt0yi0ment0xh0mjnt0wg0mont' +
    '0vg0munt0uf0mznt0tf0n5nt0sf0nant0re0ngnt0qe0nmnt0pf0nrmt0of0nxmt0nf0o3mt0mg0o9mt0fn0pgmt0ep0pnlt' +
    '0dr0ptlt0ct0q0lt0bv0q6lt0ax0qdlt0a00qklt0930qqlt0860qxlt06c0rblt4ne0n4lt4li0mslt4kk0mnlt4jm0mhlt' +
    '4cv0lfmt4bw0lamt4aw0l5mt49x0l0mt48x0kvmt47y0kqmt46y0kmmt45y0khnt44y0kcnt43y0k8nt42x0k3nt41x0jzns' +
    '40w0juns3zw0jqnt3yv0jmns3xu0jins3wu0jent3vt0jans3us0j6ns3tq0j2ns3sp0iyns3ro0ivos3qm0iros3pl0ioos' +
    '3oj0ilos3ni0ihos3mg0ieos3le0ibos3kc0i8os3ja0i5os3i80i2os3h60i0os3g40hxos3f20huos3e00hsos3cx0hqos' +
    '3bv0hnos3as0hlos39q0hjos38n0hhos37l0hfos36i0hdos35f0hcos34c0haos33a0h8os3270h7os3140h6os3010h5ps' +
    '2yy0h3os2xv0h2os2ws0h1os2vp0h1ps2um0h0os2tj0gzps2sf0gzps2rc0gyps2q90gyps2p60gyps2o30gyps2n00gyps' +
    '2lw0gyps2kt0gyps2jq0gyps2in0gyps2hj0gzps2gg0gzps2fd0h0ps1pc0iaos1m50ijos1l20imos1k00iqos1iy0itos' +
    '1hw0ixos1gu0j1os1fs0j4os1ep0j8os1do0jcos1bk0jlos1ai0jpot19h0jtos18f0jyns17e0k2ns16c0k7nt15b0kbnt' +
    '14a0kgnt1390klnt1280kqnt1170kvnt1060l0nt0z60l5nt0y50lant0x50lfnt0w40llnt0v40lqnt0u40lwnt0t40m1nt' +
    '0s40m7mt0r40mcmt0q50mimt0p50momt0o60mumt0n70n0mt0m80n6mt0l90ncmt0ka0nimt0jb0nomt0id0nvmt0he0o1mt' +
    '0gg0o7lt0fi0oelt0ek0oklt0dm0orlt0co0oxlt0br0p4lt0at0palt09w0phlt08z0polt0820pvkt4js0lelt4iu0l8lt' +
    '4hv0l2lt4c40k6mt4b50k1mt4a60jwmt4970jrmt4880jmmt4780jimt4690jdms4590j8ms4490j4mt43a0izms42a0ivns' +
    '41a0iqns40a0imns3z90iins3y90iens3x90i9ns3w80i5ns3v80i2ns3u70hyns3t60huns3s50hqns3r40hnns3q30hjns' +
    '3p20hgns3o10hdns3n00h9ns3ly0h6ns3kx0h3ns3jw0h0os3iu0gxos3ht0guos3gr0gsos3fp0gpos3en0gnos3dm0gkos' +
    '3ck0gios3bi0gfos3ag0gdos39e0gbos38c0g9os3790g7os3670g6os3550g4os3430g2os3300g1os31y0g0os30w0fyos' +
    '2zt0fxos2yr0fwos2xo0fvos2wm0fuos2vj0ftos2uh0fsos2te0fsos2sb0fros2r90fros2q60fqos2p30fqos2o10fqos' +
    '2my0fqos2lv0fqos2kt0fqos2jq0fros2in0fros2hk0fros2gi0fsos2ff0ftos2ec0ftos1mk0hbos1li0heos1kg0hios' +
    '1je0hlos1id0hpos1hb0htos1g90hwos1f80i0os1e60i4ns1d50i8ns1b20ihns1a10ilns1900ipns17z0iuns16y0iyns' +
    '15x0j3ns14w0j8ns13v0jcns12v0jhns11u0jmns10u0jrns0zt0jwnt0yt0k1ns0xt0k7ns0wt0kcnt0vt0khnt0ut0knmt' +
    '0tu0ksmt0su0kymt0rv0l4mt0qv0l9mt0pw0lfmt0ox0llmt0ny0lrmt0mz0lxmt0m00m3mt0l20m9mt0k30mfmt0j50mmmt' +
    '0i60mslt0h80mylt0gb0n5lt0fd0nblt0ef0nilt0dh0nolt0ck0nvlt0bn0o2lt0aq0o8lt09t0oflt4nm0kylt4jx0kalt' +
    '4iz0k5lt4i10jzlt48h0ijms47i0iems46j0i9ms45k0i4ms44l0i0ms43l0hvms42m0hrms41m0hmms40m0hims3zn0hems' +
    '3yn0hams3xn0h5ns3wn0h1ns3vn0gxns3um0guns3tm0gqns3sm0gmns3rl0gins3ql0gfns3pk0gcns3oj0g8ns3nj0g5ns' +
    '3mi0g2ns3lh0fyns3kg0fwns3jf0fsns3ie0fqns3hd0fnns3gc0fkns3fa0fios3e90ffns3d80fdos3c60faos3b50f8os' +
    '3a30f6os3920f4os3800f2os36y0f0os35x0eyos34v0exos33t0evos32r0euos31p0esos30o0eros2zm0eqos2yk0epos' +
    '2xi0eoos2wg0enos2ve0emor2uc0elor2t90elos2s70ekor2r50ekor2q30ekor2p10ejos2nz0ejor2mw0ejor2lu0ejos' +
    '2ks0ejor2jq0ekor2io0ekos2hl0ekor2ef0emos1mz0g3ns1ly0g7os1kw0gans1jv0geos1it0ghns1hs0glns1gr0gpns' +
    '1fq0gsns1ep0gwns1do0h0ns15i0i0ns14i0i4ns13h0i9ns12h0iens11h0ijns10h0ions0zh0itns0yh0iymt0xi0j4ms' +
    '0wi0j9ms0vi0jems0uj0jkms0tk0jpms0sl0jvmt0rm0k1mt0qn0k6mt0po0kcmt0op0kimt0nq0komt0ms0kumt0lt0l0mt' +
    '0kv0l6mt0jx0ldmt0iz0ljlt0i10lplt0h30lwlt0g60m2lt0f80m9lt0eb0mflt0dd0mmlt4u00l1kt4t40kvkt4rc0kjkt' +
    '4pj0k7kt4np0jvlt4ms0jplt4lv0jjlt4ky0jdlt4k10j7lt4j40j2lt4gb0illt4ef0ials48q0hfms47r0hbms46t0h6ms' +
    '45u0h1ms44v0gwms43w0gsms42x0gnms41y0gjms40y0gems3zz0gams3z00g6ms3y00g2ms3x10fyms3w10fums3v10fqms' +
    '3u10fmms3t10fims3s10fens3r10fbns3q10f7ns3p10f4ns3o10f1ns3n00exns3m00euns3l00erns3jz0eons3iy0elns' +
    '3hy0ejns3gx0egns3fw0edns3ew0eans3dv0e8ns3cu0e6nr3bt0e3nr3as0e1nr39r0dznr38q0dxnr37p0dvnr36n0dtnr' +
    '35m0dsnr34l0dqnr33k0donr32i0dnor31h0dmor30f0dkor2ze0djnr2yd0dior2xb0dhor2w90dgor2v80dfor2u60dfor' +
    '2t50deor2s30deor2r20ddor2q00ddor2oy0ddor2nx0dcor2mv0ddor2lt0ddor2kr0ddor2jq0ddor2io0ddor2hm0deor' +
    '2gl0deor2fj0dfor2eh0dgor2ce0dior1md0ezns1lc0f3ns1kb0f6ns1ja0fans1i90fdns1h90fhns1g80flns1f70fpns' +
    '1e70ftns1640grns1540gwns1440h1ns1340h6ms1250hbms1150hgms1050hlms0z60hqms0y60hvms0x70i0ms0w80i6ms' +
    '0v90ibms0ua0ihmt0tb0inms0sc0isms0rd0iyms0qf0j4mt0pg0jams0oi0jfmt0nj0jmlt0ml0jslt0ln0jylt0kp0k4lt' +
    '0jr0kalt0iu0khlt0hw0knlt0gz0ktlt0f40l6lt4sa0jmkt4re0jgkt4qh0jakt4pl0j4kt4op0iykt4ns0islt4mw0imlt' +
    '4lz0igkt4l20ialt4k50i4lt4j80hzlt4ib0htlt4he0hnls4gg0hilt4fj0hcls4el0h7ls4do0h2ls4cq0gwls4bs0grls' +
    '4au0gmls49w0ghls48y0gcls4800g7ms4710g2ms4630fyms4540ftms4460foms4370fkms4280ffms41a0fbms40b0f7ms' +
    '3zc0f2ms3yd0eyms3xe0eums3we0eqms3vf0emms3ug0eims3tg0eems3sh0ebms3rh0e7ms3qh0e4ms3pi0e0ms3oi0dxms' +
    '3ni0dunr3mi0dqnr3li0dnns3ki0dknr3ji0dhnr3ii0denr3hi0dcnr3gh0d9nr3fh0d6nr3eh0d4nr3dg0d1nr3cg0cznr' +
    '3bf0cxnr3af0cvnr39e0ctnr38e0crnr37d0cpnr36c0cnnr35c0clnr34b0cknr33a0cinr3290chnr3180cfnr3070cenr' +
    '2z60cdnr2y50ccnr2x40cbnr2w30canr2v20c9nr2u10c9nr2t00c8nr2rz0c7nr2qy0c7nr2px0c7nr2ow0c6nr2nu0c6nr' +
    '2mt0c6nr2ls0c6nr2kr0c7nr2jq0c7nr2ek0c9nr2di0canr1ls0dwnr1hq0eans1gq0eens1fq0eins1eq0elns1bp0eyns' +
    '18q0fbms17q0ffms16q0fkms15q0foms14r0ftms13r0fyms12s0g3ms11t0g8ms10t0gdms0zu0gims0yv0gnms0xw0gsms' +
    '0wx0gyms0vy0h3ms0v00h9ms0u10hems0t20hkms0s40hqms0r60hvms0q70i1mt4rf0idkt4qj0i7kt4pn0i1kt4or0hvkt' +
    '4nv0hpkt4my0hjkt4m20hdkt4l50h7kt4k90h1lt4jc0gwlt4if0gqls4hi0gklt4gl0gfls4fo0g9ls4er0g4ls4dt0fzls' +
    '4cw0ftls4by0fols4b10fjls4a30fels4950f9ls4870f4ls47a0ezls46b0evls45d0eqls44f0ells43h0ehms42j0ecms' +
    '41k0e8ms40m0e3ms3zn0dzms3yo0dvms3xq0drms3wr0dnms3vs0djms3ut0dfms3tu0dbms3sv0d7ms3rw0d4mr3qx0d0mr' +
    '3px0cxmr3oy0ctmr3nz0cqmr3mz0cnmr3m00ckmr3l00chmr3k10cemr3j10cbmr3i10c8mr3h20c5mr3g20c2mr3f20c0nr' +
    '3e20bymr3d20bvnr3c20btnr3b20brnr3a20bonr3920bmnr3820blnr3710bjnr3610bhnr3510bfnr3410benr3300bcnr' +
    '3200bbnr3100b9nr2zz0b8nr2yz0b7nr2xy0b6nr2wy0b5nr2vx0b4nr2ux0b3nr2tw0b3nr2sw0b2nq2rv0b2nr2qu0b1nr' +
    '2pu0b1nq2ot0b1nq2ns0b1nr2ms0b1nq2dm0b5nr2cl0b6nr1ua0c2nr1ta0c4nr1i80d3nr1d90dmmr1ca0drms1ba0dvms' +
    '1aa0dzms19b0e3ms18c0e8ms17c0ecms16d0ehms15e0emms14f0eqms13f0evms12g0f0ms11i0f5ms10j0fams0zk0ffms' +
    '0yl0flms0xn0fqms0wo0fvms0tt0gcms0sv0ghms0rx0gnls4ot0gskt4nx0gmkt4n10ggkt4m50gakt4l80g4kt4kc0fykt' +
    '4jf0ftkt4ij0fnks4hm0filt4gp0fcls4ft0f6ls4ew0f1ls4dz0ewls4d10erls4c40ells4b70egls4aa0ebls49c0e6ls' +
    '48f0e1ls47h0dwls46j0dsls45m0dnls44o0dils43q0dels42s0d9ls41u0d5ls40w0d0ls3zy0cwls3yz0csls3y10coms' +
    '3x30ckms3w40cgmr3v60ccmr3u70c8mr3t90c4mr3sa0c1mr3rb0bxmr3qc0bumr3pe0bqmr3of0bnmr3ng0bkmr3mh0bgmr' +
    '3li0bdmr3ki0bamr3jj0b7mr3ik0b5mr3hl0b2mr3gl0azmr3fm0axmr3en0aumr3dn0asmr3co0apmr3bo0anmr3ap0almq' +
    '39p0ajmr38p0ahmr37q0afmq36q0admr35q0abmq34q0aamq33r0a8mq32r0a7mq31r0a5nq30r0a4mq2zr0a3nq2yr0a2nq' +
    '2xr0a1nq2wr0a0nq2vr09znq2ur09ynq2tr09xnq2sr09xnq2rr09xnq2qr09wnq2pr09wnq2or09wnq2nq09wnq2mq09wnq' +
    '2lq09wnq2kq09wnq2jq09wnq2ep09znq1vn0atnr1un0awnr1tn0aymr1lp0bmmr1kp0bqmr1jp0btmr1iq0bxmr1hq0c0mr' +
    '1gr0c4mr1dt0cgmr1cu0ckmr1bu0comr1av0csmr19w0cwmr18x0d1mr17y0d5ms16z0dams1600dems1520djms1430doms' +
    '1340dtms1260dyms1170e3ms1090e8ms0za0edms0yc0eims0vh0eyls0uj0f4ls4n30fdkt4kf0ewkt4im0ekkt4hq0efks' +
    '4gt0e9ks4fx0e4ls4f00dyls4e30dtls4d60dols4ca0djls4bd0dels4af0d8ls49i0d3ls48l0czls47o0culs46r0cpls' +
    '45t0ckls44w0cgls43y0cbls4310c6ls4230c2ls4150byls4070bulr3za0bplr3yc0bllr3xe0bhlr3wg0bdlr3vi0b9lr' +
    '3uj0b5lr3tl0b2lr3sn0aymr3rp0aumr3qq0armr3ps0anmr3ou0akmr3nv0ahmr3mw0aemr3ly0abmr3kz0a8mr3k10a5mr' +
    '3j20a2mr3i309zmq3h409wmr3g509umq3f609rmq3e709pmq3d809mmq3c909kmq3ba09imq3ab09gmq39c09emq38d09cmq' +
    '37e09amq36e098mq35f096mq34g095mq33h093mq32h092mq31i090mq30i08zmq2zj08ymq2yk08xmq2xk08wmq2wl08vmq' +
    '2vl08umq2um08tmq2tm08tmq2sm08smq2rn08smq2qn08rmq2po08rmq2oo08rmq2no08rmq2mp08rmq2lp08rmq2kp08rmq' +
    '2jq08rmq2iq08smq26u093mq25u094mq1wy09mmq1vz09omq1uz09qmq1u009tmq1t009wmq1s109ymq1m50agmr1l60akmr' +
    '1k70anmr1j80armr1i90aumr1ha0aymr1fc0b6mr1ed0bamr1cf0bimr1bg0bmmr19j0bumr18k0bzmr17m0c3mr16n0c8mr' +
    '15p0ccmr13s0cmms12u0crms10y0d0ls0zz0d6ls0x50dlls4jl0dnkt4ip0dhkt4ht0dcks4gx0d6ks4g00d1ks4f40cwks' +
    '4e70cqks4db0clls4ce0cgls4bi0cbls4al0c6ls49o0c1ls48r0bwls47u0brls46x0bmls4600bils4530bdls4460b9ls' +
    '4390b4lr42b0b0lr41e0avlr40h0arlr3zj0anlr3ym0ajlr3xo0aflr3wr0ablr3vt0a7lr3uv0a3lr3tx09zlr3sz09wlr' +
    '3s209slr3r409plr3q609llr3p809ilr3oa09emr3nc09blq3md098lr3lf095mq3kh092lq3jj08zmq3ik08wmq3hm08umq' +
    '3go08rmq3fp08omq3er08mmq3ds08kmq3cu08hmq3bv08fmq3ax08dmq39y08bmq38z089mq380087mq372085mq363084mq' +
    '354082mq345080mq33707zmq32807xmq31907wmq30a07vmq2zb07umq2yc07tmq2xd07smq2we07rmq2vf07qmq2ug07pmq' +
    '2th07pmq2si07omq2rj07omq2qk07nmp2pl07nmq2ol07nmq2nm07nmq2mn07nmq2lo07nmq2kp07nmq29y07umq28z07wmq' +
    '28007xmq27007ymq261080mq1z808cmq1y808fmq1x908hmq1wa08jmq1vb08mmq1uc08omq1te08rmq1sf08tmq1ln09emq' +
    '1ko09imq1jp09lmr1ir09pmr1hs09smr1fv0a0mr1ex0a4mr1dy0a7mr1c10agmr1960asmr17a0b1lr13i0bklr12k0bols' +
    '11m0btls10o0byls4eb0boks4df0biks4cj0bdks4bm0b8ks4aq0b3ks49t0ayks48x0atks4800apks4730akls4670afls' +
    '45a0ablr44d0a6lr43g0a2lr42j09xlr41m09tlr40p09plr3zs09llr3yv09glr3xy09clr3x1099lr3w3095lr3v6091lr' +
    '3u908xlr3tb08ulr3se08qlr3rg08mlq3qj08jlr3pl08glq3oo08clq3nq089lq3ms086lq3lu083lq3kx080lq3jz07xlq' +
    '3j107ulq3i307slq3h507plq3g707mlq3f907klq3eb07ilq3dd07flq3cf07dlq3bh07blq3aj079lq39l077lq38m075lq' +
    '37o073mq36q071mp35s070mp34t06ymq33v06wlp32x06vmp31y06tmp31006smp30106rmp2z306qmp2y406pmp2x606omp' +
    '2ua06mmp2tc06lmp2sd06kmp2rf06kmp2qg06kmp2pi06kmp2oj06jmp2nk06jmp2mm06jmp23c071mp22e073mp21f074mq' +
    '20h076mq1zi078mp1yj07amq1xl07dmq1wm07fmq1vo07hmq1up07kmq1tr07mmq1ru07smq1hd08rmq1ge08ulq1fg08ylq' +
    '1ei092lq1dk096lq1bo09elr19t09mlr18v09qlr1540a8lr12b0anlr11d0aslr4bq0a6ks49y09wks49209rks48509mks' +
    '47909iks46d09dkr45g098kr44k094kr43n090kr42r08vlr41u08rkr40x08nlr40008jlr3z408flr3y708alr3xa087lr' +
    '3wd083lr3vg07zlr3uj07vlq3tm07slq3sp07olq3rs07llq3qv07hlq3py07elq3p107blq3o3077lq3n6074lq3m9071lq' +
    '3lb06ylq3ke06wlq3jh06tlq3ij06qlq3hm06nlq3go06llq3fr06ilq3et06glq3dw06elp3cy06blp3c0069lp3b3067lp' +
    '3a5065lp397063lp38a061lp37c05zlp36e05ylp35g05wlp34i05ulp33l05tlp32n05slp31p05qlp30r05plp2zt05olp' +
    '2xx05mlp2wz05llp2w105klp2v305jlp2u505jlp2t705ilp2s905ilp2rb05hlp2qd05hlp2pe05hlp2og05glp25h05ulp' +
    '24j05wlp23l05xlp22n05zlp21p061lp20r063lp1zt065lp1yu067lp1xw069lp1wy06blp1w006dlp1v206glp1u406ilp' +
    '1t606llq1s806nlp1ra06qlq1g007tlq1c9088lq1af08glr18k08plr15r092lr43t07ykr42x07tkr3xj075kr3wm071kr' +
    '3vq06ylq3ut06ulq3t006nlq3s306jlq3r606glq3qa06clq3pd069lq3og066lq3nj063lq3mm060lq3lq05xlq3kt05ulq' +
    '3jw05rlq3iz05plp3i205mlp3h505klp3g805hlp3fa05flp3ed05clp3dg05alp3cj058lp3bm056lp3ap054lp39r052lp' +
    '34704rlp33a04qlp2r704flo27k04plp26m04qlo25p04slp24r04tlp23t04vlp22w04wlp21y04ylp211050lp203052lp' +
    '1z5054lp1y8056lp1xa058lp1wd05alp1vf05dlp1uh05flp1tk05hlp1sm05klp1rp05nlp1qr05plp1pu05slp1ow05vlp' +
    '1nz05ylp1n1061lp1m4064lq1jc06elq1ie06hlq1hh06llq1gk06olq1fm06slq1ep06wlq1ds06zlq1cv073lq1bx077lq' +
    '1b007blq1a307flq3ta05lkq3se05ikq3rh05fkq3ql05bkq3pp058kq3os055kq3nw052kq3mz04zkp3m304wlp3l604tkp' +
    '3ka04rkp3jd04olp3ih04llp3hk04jkp3go04glp3fr04elp3c4045lp3b7043lp3ab041lp33x03plo33003olo28o03llo' +
    '26t03olo25w03qlo24z03rlo24203slo23503ulo22803wlo21a03ylo20d03zlo1zg041lo1yj043lp1xm045lp1wp048lp' +
    '1vs04alp1uu04clp1tx04elp1t004hlp1s304jlp1r604mlp1q904plp1pc04slp1of04ulp1ml050lp1lo054lp1ju05alp' +
    '1ix05dlp1i005hlq1h305klq1g605olq1f905rlq1dg05zlq3p4044kp3o8042kp3nc03ykp3mf03wkp3lj03tkp3kn03qkp' +
    '3iv03lkp3h303gkp3g703ekp3fa03bkp39002xko38402vko36b02sko35f02rko34i02pko27002nlo26402olo25702qlo' +
    '24a02rlo23e02tlo22h02ulo21k02wko20o02ylo1zr030lo1yu031lo1xy033ko1x1036lo1w4038lo1v803ako1ub03clo' +
    '1te03fko1si03hlo1rl03kkp1qo03mko1ps03plp1nz03ulp1n203xlp1m5040kp1l9043kp1kc046kp1jg04akp1ij04dkp' +
    '3lw02tkp3l002qkp3k402nkp3dy027ko2p301bkn2na01bkn2me01bkn29001kkn28401lkn27701mkn26b01nkn25f01pkn' +
    '24j01qkn23m01skn22q01tko21u01vko20y01xko20201yko1z5020ko1y9022ko1xd024ko1uo02bko1ts02dko1sw02fko' +
    '3hv01hko3di016ko3br012ko37e00tkn36j00skn35n00qkn34s00pkn33w00okn32500lkn31a00kkn30e00jkn2zj00ikn' +
    '2te00dkn2rn00ckn2pv00ckn2n800bkn2bt00hkn2ax00ikn29600kkn25n00pkn24r00qkn23v00rkn23000tkn22400ukn' +
    '21800wkn1zh010kn1yl011kn'

export interface GlobeField {
    count: number
    /** Centres, in the field's own coordinate space. */
    x: Float32Array
    y: Float32Array
    /** Radii. Not one number: a cell near the limb of the globe is foreshortened,
     *  and that per-dot squash is what makes a flat field read as a sphere. */
    rx: Float32Array
    ry: Float32Array
}

let cached: GlobeField | null = null

/** Decode the field. Cached: the arrays are immutable geometry, so a second
 *  instance of the graphic shares them rather than re-parsing 27 KB. */
export function decodeGlobeField(): GlobeField {
    if (cached) return cached

    const count = FIELD.length / STRIDE
    const field: GlobeField = {
        count,
        x: new Float32Array(count),
        y: new Float32Array(count),
        rx: new Float32Array(count),
        ry: new Float32Array(count)
    }

    for (let i = 0; i < count; i++) {
        let at = i * STRIDE
        field.x[i] = parseInt(FIELD.slice(at, (at += POS)), 36) / UNIT
        field.y[i] = parseInt(FIELD.slice(at, (at += POS)), 36) / UNIT
        field.rx[i] = parseInt(FIELD.slice(at, (at += SIZE)), 36) / UNIT / 2
        field.ry[i] = parseInt(FIELD.slice(at, at + SIZE), 36) / UNIT / 2
    }

    cached = field
    return field
}
